ALTER TYPE "MediaVisibility" ADD VALUE IF NOT EXISTS 'REGISTERED';
ALTER TABLE "DealerCompany" ADD COLUMN "profile" JSONB NOT NULL DEFAULT '{}', ADD COLUMN "catalogPolicy" JSONB NOT NULL DEFAULT '{}', ADD COLUMN "purchaseSettings" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "DealerMember" ADD COLUMN "active" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "DealerApplication" ADD COLUMN "agreementVersion" TEXT NOT NULL DEFAULT 'dealer-2026-09', ADD COLUMN "agreedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, ADD COLUMN "consentIp" TEXT, ADD COLUMN "claimTokenHash" TEXT, ADD COLUMN "claimExpiresAt" TIMESTAMP(3);
CREATE UNIQUE INDEX "DealerApplication_claimTokenHash_key" ON "DealerApplication"("claimTokenHash");
ALTER TABLE "DealerRfq" ADD COLUMN "targetDeliveryAt" TIMESTAMP(3), ADD COLUMN "attachmentIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "rejectionReason" TEXT;
ALTER TABLE "DealerQuote" ADD COLUMN "discountCents" INTEGER NOT NULL DEFAULT 0, ADD COLUMN "paymentTerms" TEXT NOT NULL DEFAULT 'PREPAID', ADD COLUMN "deliveryTerms" TEXT;
ALTER TABLE "PurchaseOrder" ADD COLUMN "billingAddress" JSONB NOT NULL DEFAULT '{}', ADD COLUMN "customerPoNumber" TEXT, ADD COLUMN "paymentMethod" TEXT NOT NULL DEFAULT 'BANK_TRANSFER', ADD COLUMN "paymentTerms" TEXT NOT NULL DEFAULT 'PREPAID';
ALTER TABLE "PurchaseOrderItem" ADD COLUMN "shippedQuantity" INTEGER NOT NULL DEFAULT 0;
UPDATE "PurchaseOrderItem" i SET "shippedQuantity"=i."quantity" FROM "PurchaseOrder" o WHERE i."orderId"=o."id" AND o."status" IN ('SHIPPED','COMPLETED');
ALTER TABLE "MediaAsset" ADD COLUMN "checksum" TEXT, ADD COLUMN "alt" TEXT NOT NULL DEFAULT '', ADD COLUMN "usageLocations" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "version" INTEGER NOT NULL DEFAULT 1, ADD COLUMN "previousVersionId" TEXT, ADD COLUMN "scanStatus" TEXT NOT NULL DEFAULT 'LEGACY_UNSCANNED', ADD COLUMN "derivatives" JSONB NOT NULL DEFAULT '[]', ADD COLUMN "companyIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "productIds" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[], ADD COLUMN "qualification" BOOLEAN NOT NULL DEFAULT false;
UPDATE "MediaAsset" SET "qualification"=true WHERE "uploadedById" IS NULL AND "visibility"='DEALER_ONLY';
CREATE INDEX "MediaAsset_checksum_visibility_idx" ON "MediaAsset"("checksum","visibility");
CREATE TABLE "DealerAddress"("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL REFERENCES "DealerCompany"("id") ON DELETE CASCADE,"label" TEXT NOT NULL,"kind" TEXT NOT NULL DEFAULT 'BOTH',"address" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE INDEX "DealerAddress_companyId_idx" ON "DealerAddress"("companyId");
CREATE TABLE "DealerInvitation"("id" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL REFERENCES "DealerCompany"("id") ON DELETE CASCADE,"email" TEXT NOT NULL,"role" "DealerMemberRole" NOT NULL DEFAULT 'VIEWER',"tokenHash" TEXT NOT NULL UNIQUE,"expiresAt" TIMESTAMP(3) NOT NULL,"consumedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "DealerInvitation_companyId_email_idx" ON "DealerInvitation"("companyId","email");
CREATE TABLE "DealerApplicationDraft"("userId" TEXT PRIMARY KEY,"data" JSONB NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "DealerProcurementCart"("userId" TEXT PRIMARY KEY,"companyId" TEXT NOT NULL,"lines" JSONB NOT NULL DEFAULT '[]',"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "PurchaseOrderShipment"("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL REFERENCES "PurchaseOrder"("id") ON DELETE CASCADE,"carrier" TEXT NOT NULL,"trackingNumber" TEXT NOT NULL,"lines" JSONB NOT NULL,"shippedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"dedupeKey" TEXT NOT NULL UNIQUE);
CREATE INDEX "PurchaseOrderShipment_orderId_idx" ON "PurchaseOrderShipment"("orderId");
