const en = {
  title: "WEMOVE wooden marble runs",
  allProducts: "All Products",
  description: "Explore WEMOVE wooden marble-run sets and mechanical modules.",
  eyebrow: "WEMOVE collection",
  count: (n: number) => `${n} products in the WEMOVE collection.`,
  browse: "Browse sets and mechanical modules, then compare details and guidance.",
  search: "Search products",
  category: "Product category",
  allCategories: "All categories",
  age: "Age",
  ages: (min: number, max: number | null) =>
    max === null ? `Ages ${min}+` : `Ages ${min}–${max}`,
  scene: "Scene",
  all: "All",
  scenes: {
    Indoor: "Indoor",
    Outdoor: "Outdoor",
    Family: "Family",
    School: "School",
  },
  skill: "Skill",
  skillPlaceholder: "Balance, coordination…",
  minPrice: "Minimum price",
  maxPrice: "Maximum price",
  availability: "Availability",
  inStock: "In stock",
  sort: "Sort",
  featured: "Featured",
  newest: "Newest",
  priceAsc: "Price: low to high",
  priceDesc: "Price: high to low",
  name: "Name",
  showResults: "Show results",
  preview: "WEMOVE catalog preview",
  unavailable: "The live catalog is taking a timeout.",
  unavailableDescription:
    "The storefront is ready, but product data is not reachable right now. Try again shortly or contact our team for the current range.",
  retry: "Try again",
  contact: "Contact us",
  noMatch: "No exact match yet",
  noMatchDescription: "Clear a filter or try a broader product name.",
  clear: "Clear filters",
  browseCategories: "Browse categories",
  recommendations: "Explore these products",
  outOfStock: "Out of stock",
  dealerPrice: "Check dealer price and minimum order",
  from: (price: string) => `From ${price}`,
  dealerCatalog: "Authorized dealer catalog",
  compare: "Compare",
  pagination: "Product pagination",
  previous: "Previous",
  next: "Next",
  page: (page: number, total: number) => `Page ${page} of ${total}`,
};

const zh: typeof en = {
  title: "积木玩具",
  allProducts: "全部产品",
  description:
    "探索 WEMOVE 实木滚珠轨道套装与机械机关模块，查看参数、适龄建议和电子说明书。",
  eyebrow: "WEMOVE 产品系列",
  count: (n) => `共 ${n} 款产品。`,
  browse: "浏览套装与机关模块，并通过搜索和产品对比辅助选择。",
  search: "搜索产品",
  category: "产品分类",
  allCategories: "全部分类",
  age: "年龄",
  ages: (min, max) => (max === null ? `${min} 岁及以上` : `${min}–${max} 岁`),
  scene: "使用场景",
  all: "全部",
  scenes: { Indoor: "室内", Outdoor: "户外", Family: "家庭", School: "学校" },
  skill: "培养能力",
  skillPlaceholder: "例如：平衡、协调",
  minPrice: "最低价格",
  maxPrice: "最高价格",
  availability: "库存状态",
  inStock: "有货",
  sort: "排序方式",
  featured: "推荐优先",
  newest: "最新上架",
  priceAsc: "价格：从低到高",
  priceDesc: "价格：从高到低",
  name: "产品名称",
  showResults: "查看结果",
  preview: "WEMOVE 产品目录预览",
  unavailable: "产品目录暂时无法加载。",
  unavailableDescription:
    "目前无法获取产品数据，请稍后重试，或联系我们了解现有产品。",
  retry: "重新加载",
  contact: "联系我们",
  noMatch: "暂无匹配的产品",
  noMatchDescription: "请减少筛选条件，或尝试其他产品名称。",
  clear: "清除筛选",
  browseCategories: "浏览产品分类",
  recommendations: "看看这些产品",
  outOfStock: "缺货",
  dealerPrice: "查看经销商价格与起订量",
  from: (price) => `${price} 起`,
  dealerCatalog: "经销商授权产品目录",
  compare: "比较产品",
  pagination: "产品分页",
  previous: "上一页",
  next: "下一页",
  page: (page, total) => `第 ${page} 页，共 ${total} 页`,
};

export function catalogLanguage(locale: string) {
  const language = locale.split("-")[0];
  return language === "zh" || language === "en" ? language : null;
}

export function catalogCopy(locale: string) {
  return catalogLanguage(locale) === "zh" ? zh : en;
}
