const en = {
  title: "Sign in",
  welcome: "Welcome back",
  intro:
    "Enter your email and password. We’ll open the workspace linked to your account.",
  email: "Email",
  password: "Password",
  forgot: "Forgot password?",
  code: "Authenticator code",
  verify: "Verify and sign in",
  busy: "Signing in…",
  mfaTitle: "Verify your identity",
  mfaIntro: "Enter the current six-digit code from your authenticator.",
  setup:
    "Add this setup key to your authenticator, then enter its six-digit code.",
  setupKey: "Authenticator setup key",
  openAuthenticator: "Open authenticator",
  restart: "Use a different account",
  newHere: "New to WEMOVE?",
  register: "Create an account",
  home: "Back to the store",
  customer: "Customer account",
  customerDetail: "Your orders, saved products and delivery addresses.",
  dealer: "Business purchasing",
  dealerDetail: "Your company’s catalogue, quotes and purchase orders.",
  staff: "Operations workspace",
  staffDetail:
    "Manage products, content and orders with your assigned permissions.",
  privacy: "Privacy",
  terms: "Terms",
  invalid: "The email or password is incorrect.",
  expired: "Your verification expired. Enter your email and password again.",
  codeError: "Check the current authenticator code and try again.",
  unavailable: "Sign-in is temporarily unavailable. Please try again.",
  limited: "Too many attempts. Please wait a while before trying again.",
};
type LoginCopy = Record<keyof typeof en, string>;
const messages: Record<string, LoginCopy> = {
  en,
  zh: {
    title: "登录",
    welcome: "欢迎回来",
    intro: "输入邮箱和密码，登录后自动进入你的账户或工作台。",
    email: "邮箱",
    password: "密码",
    forgot: "忘记密码？",
    code: "验证器动态码",
    verify: "验证并登录",
    busy: "正在登录…",
    mfaTitle: "验证身份",
    mfaIntro: "请输入验证器中当前显示的六位动态码。",
    setup: "将此设置密钥添加到验证器，然后输入生成的六位动态码。",
    setupKey: "验证器设置密钥",
    openAuthenticator: "打开验证器",
    restart: "使用其他账号",
    newHere: "还没有 WEMOVE 账号？",
    register: "创建账号",
    home: "返回商城",
    customer: "消费者中心",
    customerDetail: "查看订单、收藏商品并管理收货地址。",
    dealer: "企业采购门户",
    dealerDetail: "查看企业授权商品、询报价及采购订单。",
    staff: "运营管理后台",
    staffDetail: "根据分配的权限管理商品、内容与订单。",
    privacy: "隐私政策",
    terms: "使用条款",
    invalid: "邮箱或密码不正确。",
    expired: "身份验证已过期，请重新输入邮箱和密码。",
    codeError: "请核对当前验证器动态码后重试。",
    unavailable: "登录服务暂时不可用，请稍后重试。",
    limited: "尝试次数过多，请稍后重试。",
  },
  fr: {
    title: "Se connecter",
    welcome: "Heureux de vous revoir",
    intro:
      "Saisissez votre e-mail et votre mot de passe pour accéder à votre espace.",
    email: "E-mail",
    password: "Mot de passe",
    forgot: "Mot de passe oublié ?",
    code: "Code de l’authentificateur",
    verify: "Vérifier et se connecter",
    busy: "Connexion…",
    mfaTitle: "Vérifiez votre identité",
    mfaIntro: "Saisissez le code à six chiffres de votre authentificateur.",
    setup:
      "Ajoutez cette clé à votre authentificateur, puis saisissez le code à six chiffres.",
    setupKey: "Clé de configuration",
    openAuthenticator: "Ouvrir l’authentificateur",
    restart: "Utiliser un autre compte",
    newHere: "Nouveau chez WEMOVE ?",
    register: "Créer un compte",
    home: "Retour à la boutique",
    customer: "Compte client",
    customerDetail: "Vos commandes, vos favoris et vos adresses de livraison.",
    dealer: "Achats professionnels",
    dealerDetail:
      "Le catalogue, les devis et les commandes de votre entreprise.",
    staff: "Espace de gestion",
    staffDetail:
      "Gérez les produits, les contenus et les commandes selon vos droits.",
    privacy: "Confidentialité",
    terms: "Conditions",
    invalid: "L’e-mail ou le mot de passe est incorrect.",
    expired:
      "La vérification a expiré. Saisissez à nouveau votre e-mail et votre mot de passe.",
    codeError: "Vérifiez le code actuel et réessayez.",
    unavailable:
      "La connexion est temporairement indisponible. Réessayez plus tard.",
    limited: "Trop de tentatives. Veuillez patienter avant de réessayer.",
  },
  de: {
    title: "Anmelden",
    welcome: "Willkommen zurück",
    intro:
      "Geben Sie Ihre E-Mail und Ihr Passwort ein, um Ihren Kontobereich zu öffnen.",
    email: "E-Mail",
    password: "Passwort",
    forgot: "Passwort vergessen?",
    code: "Authenticator-Code",
    verify: "Bestätigen und anmelden",
    busy: "Anmeldung…",
    mfaTitle: "Identität bestätigen",
    mfaIntro:
      "Geben Sie den aktuellen sechsstelligen Code Ihres Authenticators ein.",
    setup:
      "Fügen Sie diesen Schlüssel zum Authenticator hinzu und geben Sie den sechsstelligen Code ein.",
    setupKey: "Einrichtungsschlüssel",
    openAuthenticator: "Authenticator öffnen",
    restart: "Anderes Konto verwenden",
    newHere: "Neu bei WEMOVE?",
    register: "Konto erstellen",
    home: "Zurück zum Shop",
    customer: "Kundenkonto",
    customerDetail: "Ihre Bestellungen, Favoriten und Lieferadressen.",
    dealer: "Geschäftseinkauf",
    dealerDetail: "Katalog, Angebote und Bestellungen Ihres Unternehmens.",
    staff: "Verwaltung",
    staffDetail:
      "Verwalten Sie Produkte, Inhalte und Bestellungen mit Ihren Berechtigungen.",
    privacy: "Datenschutz",
    terms: "Bedingungen",
    invalid: "Die E-Mail oder das Passwort ist falsch.",
    expired:
      "Die Bestätigung ist abgelaufen. Geben Sie E-Mail und Passwort erneut ein.",
    codeError: "Prüfen Sie den aktuellen Code und versuchen Sie es erneut.",
    unavailable:
      "Die Anmeldung ist vorübergehend nicht verfügbar. Bitte versuchen Sie es später erneut.",
    limited:
      "Zu viele Versuche. Bitte warten Sie, bevor Sie es erneut versuchen.",
  },
};
export function loginCopy(locale: string): LoginCopy {
  return messages[locale.split("-")[0]] ?? en;
}
