const en = {
  products: "Products",
  ages: "Ages",
  guidance: "Age and supervision guidance",
  compare: "Add to comparison",
  resources: "Product resources",
  resource: "Resource",
  specifications: "Specifications",
  play: "Setup, play, care and safety",
  faq: "Product FAQ",
  related: "Related products",
  accessories: "Accessories",
  replacements: "Replacement parts",
  catalogUpdate: "Catalog update",
  unavailable: "Product unavailable",
  back: "Back to products",
  variant: "Variant",
  quantity: "Quantity",
  added: "Added to your cart.",
  guestAdded: "Saved to your guest cart. Sign in at checkout to merge it.",
  addError: "Unable to add this item. Check availability and try again.",
  notAvailable: "This product is not currently available.",
  retailer: "Find this product through a local retailer.",
  where: "Where to buy",
  contact: "Contact us",
  viewCart: "View cart",
  adding: "Adding…",
  outOfStock: "Out of stock",
  checkAvailability: "Check availability",
  preorder: "Preorder",
  backorder: "Backorder",
  addToCart: "Add to cart",
  unavailableOption: "Unavailable",
  available: "{n} available.",
  stockLevel: "Stock level",
  low: "Low",
  normal: "Normal",
  dispatch: "Estimated dispatch in {n} days.",
  share: "Share link",
  copied: "Share link copied.",
  copy: "Copy this link",
  gallery: "Product gallery",
  previous: "Previous image",
  next: "Next image",
  image: "Image",
  video: "Video",
};
type Copy = typeof en;
const zh: Copy = {
  products: "产品",
  ages: "适用年龄",
  guidance: "年龄与成人看护建议",
  compare: "加入比较",
  resources: "产品资料",
  resource: "资料",
  specifications: "产品规格",
  play: "安装、玩法、保养与安全",
  faq: "常见问题",
  related: "相关产品",
  accessories: "配件",
  replacements: "替换件",
  catalogUpdate: "产品目录更新",
  unavailable: "产品暂不可用",
  back: "返回产品目录",
  variant: "款式",
  quantity: "数量",
  added: "已加入购物车。",
  guestAdded: "已保存至访客购物车，结账登录后将合并。",
  addError: "暂时无法加入此商品，请确认库存后重试。",
  notAvailable: "此产品目前暂不可购。",
  retailer: "请通过当地经销商购买此产品。",
  where: "购买地点",
  contact: "联系我们",
  viewCart: "查看购物车",
  adding: "正在添加…",
  outOfStock: "缺货",
  checkAvailability: "请确认库存",
  preorder: "预订",
  backorder: "缺货预订",
  addToCart: "加入购物车",
  unavailableOption: "暂不可用",
  available: "可购数量：{n}。",
  stockLevel: "库存水平",
  low: "偏低",
  normal: "充足",
  dispatch: "预计 {n} 天后发货。",
  share: "分享链接",
  copied: "分享链接已复制。",
  copy: "复制此链接",
  gallery: "产品图库",
  previous: "上一张",
  next: "下一张",
  image: "图片",
  video: "视频",
};
const fr: Copy = {
  products: "Produits",
  ages: "Âges",
  guidance: "Conseils d’âge et de surveillance",
  compare: "Ajouter au comparatif",
  resources: "Documents du produit",
  resource: "Document",
  specifications: "Caractéristiques",
  play: "Installation, jeu, entretien et sécurité",
  faq: "Questions sur le produit",
  related: "Produits associés",
  accessories: "Accessoires",
  replacements: "Pièces de rechange",
  catalogUpdate: "Mise à jour du catalogue",
  unavailable: "Produit indisponible",
  back: "Retour aux produits",
  variant: "Variante",
  quantity: "Quantité",
  added: "Ajouté à votre panier.",
  guestAdded:
    "Enregistré dans votre panier invité. Connectez-vous au paiement pour le fusionner.",
  addError:
    "Impossible d’ajouter ce produit. Vérifiez la disponibilité et réessayez.",
  notAvailable: "Ce produit est actuellement indisponible.",
  retailer: "Retrouvez ce produit auprès d’un revendeur local.",
  where: "Où acheter",
  contact: "Nous contacter",
  viewCart: "Voir le panier",
  adding: "Ajout en cours…",
  outOfStock: "Rupture de stock",
  checkAvailability: "Vérifier la disponibilité",
  preorder: "Précommander",
  backorder: "Commander en réapprovisionnement",
  addToCart: "Ajouter au panier",
  unavailableOption: "Indisponible",
  available: "{n} disponibles.",
  stockLevel: "Niveau de stock",
  low: "Faible",
  normal: "Normal",
  dispatch: "Expédition estimée sous {n} jours.",
  share: "Partager le lien",
  copied: "Lien de partage copié.",
  copy: "Copier ce lien",
  gallery: "Galerie du produit",
  previous: "Image précédente",
  next: "Image suivante",
  image: "Image",
  video: "Vidéo",
};
const de: Copy = {
  products: "Produkte",
  ages: "Alter",
  guidance: "Hinweise zu Alter und Aufsicht",
  compare: "Zum Vergleich hinzufügen",
  resources: "Produktunterlagen",
  resource: "Unterlage",
  specifications: "Technische Daten",
  play: "Aufbau, Spiel, Pflege und Sicherheit",
  faq: "Fragen zum Produkt",
  related: "Ähnliche Produkte",
  accessories: "Zubehör",
  replacements: "Ersatzteile",
  catalogUpdate: "Katalogaktualisierung",
  unavailable: "Produkt nicht verfügbar",
  back: "Zurück zu den Produkten",
  variant: "Variante",
  quantity: "Menge",
  added: "Zum Warenkorb hinzugefügt.",
  guestAdded:
    "Im Gastwarenkorb gespeichert. Melden Sie sich an der Kasse an, um ihn zusammenzuführen.",
  addError:
    "Dieses Produkt konnte nicht hinzugefügt werden. Bitte Verfügbarkeit prüfen und erneut versuchen.",
  notAvailable: "Dieses Produkt ist derzeit nicht verfügbar.",
  retailer: "Dieses Produkt finden Sie bei einem Händler vor Ort.",
  where: "Händler finden",
  contact: "Kontakt",
  viewCart: "Warenkorb anzeigen",
  adding: "Wird hinzugefügt…",
  outOfStock: "Nicht auf Lager",
  checkAvailability: "Verfügbarkeit prüfen",
  preorder: "Vorbestellen",
  backorder: "Nachbestellen",
  addToCart: "In den Warenkorb",
  unavailableOption: "Nicht verfügbar",
  available: "{n} verfügbar.",
  stockLevel: "Lagerbestand",
  low: "Niedrig",
  normal: "Normal",
  dispatch: "Voraussichtlicher Versand in {n} Tagen.",
  share: "Link teilen",
  copied: "Link zum Teilen kopiert.",
  copy: "Diesen Link kopieren",
  gallery: "Produktgalerie",
  previous: "Vorheriges Bild",
  next: "Nächstes Bild",
  image: "Bild",
  video: "Video",
};
const copies: Record<string, Copy> = { en, zh, fr, de };
export const productPageLanguage = (locale: string) =>
  Object.hasOwn(copies, locale.split("-")[0]) ? locale.split("-")[0] : null;
export const productCopy = (locale = "en"): Copy =>
  copies[productPageLanguage(locale) ?? "en"];
