/** Chinese interface messages for administration; API codes remain unchanged. */
export const adminMessages: Record<string, string> = {
  "The interface supports English and Chinese. These settings control published content languages; publish complete translations before enabling them.": "界面支持中英文。以下设置控制已发布内容的语言，请先补齐并发布译文再启用。",
  "Enable Chinese content": "启用中文内容",
  "Show published English content": "显示已发布的英文内容",
  "(hidden)": "（已隐藏）",
  "· free shipping": " · 免运费",
  "· {value1} awaiting replenishment": " · {value1} 件待补货",
  "(comma separated emails)": "（多个邮箱用英文逗号分隔）",
  "(comma separated)": "（用英文逗号分隔）",
  ". Business events may provide reference, status, paymentStatus or eventKind. Missing values stop the message and record an error in the delivery queue.":
    "。业务事件可提供 reference、status、paymentStatus 或 eventKind。缺失变量会停止发送，并在投递队列记录错误。",
  "/24 selected": "/24 项已选择",
  "; SMS:": "；短信：",
  "; product updates:": "；商品更新：",
  "A blank maximum has no upper limit. Lower bounds are inclusive; upper bounds are exclusive. Fixed delivery fees apply when no rule matches. Free shipping still takes precedence.":
    "最大值留空表示不设上限。下限包含边界，上限不包含边界。未匹配规则时采用固定运费；免运费规则优先。",
  "A reported source failure preserves quantities and blocks new checkout until a healthy stock update is recorded.":
    "库存源故障时保留现有数量并暂停新结账，直到收到正常库存更新。",
  ACTIVE: "已启用",
  ARCHIVED: "已归档",
  Action: "操作",
  Activate: "启用",
  Active: "已启用",
  "Activity events: last": "行为事件：最近",
  "Add SKU": "添加 SKU",
  "Add delivery rate": "添加运费规则",
  "Add line": "添加明细",
  "Add meaningful alt text or mark this image as decorative.":
    "请填写有意义的图片替代文字，或标记为装饰图片。",
  "Add media": "添加媒体",
  "Add primary link": "添加一级链接",
  "Add regional tax rate": "添加地区税率",
  "Add secondary link": "添加二级链接",
  "Add translation": "添加译文",
  "Additional language codes (comma separated)":
    "其他语言代码（用英文逗号分隔）",
  Addresses: "地址",
  "Admin Dashboard": "管理工作台",
  "Admin Sign in": "管理员登录",
  "Admin dashboard": "管理工作台",
  Administration: "管理后台",
  After: "变更后",
  "Age and adult supervision guidance": "适用年龄与成人监护说明",
  All: "全部",
  "All measures below cover the last 30 days. Rates are percentages; blank means no eligible denominator. Product rates count consenting browser sessions, and assisted conversions match later purchases within that session. Sales use payment records and stay separate for each currency. Non-consenting visits are excluded from behavior reports.":
    "以下指标统计最近 30 天。比率以百分比显示；空值表示没有适用的统计基数。商品指标只统计已同意分析的浏览器会话，辅助转化关联同一会话中的后续购买。销售额基于支付记录并按币种分别统计。未同意分析的访问不计入行为报表。",
  "All priorities": "全部优先级",
  "All sources": "全部来源",
  "All staff": "全部员工",
  "All statuses": "全部状态",
  "Allow configured backorders": "允许已配置的缺货订购",
  "Allow configured preorders": "允许已配置的预售",
  "Alt text": "替代文字",
  "Amount (cents, mixed currencies not summed)":
    "金额（最小货币单位，不合计不同币种）",
  Analytics: "访问分析",
  Any: "不限",
  Applied: "已应用",
  "Apply filters": "应用筛选",
  "Apply reviewed import": "应用已审核的导入",
  Approve: "批准",
  "Arrange primary and secondary links, translate their labels and choose available markets.":
    "安排一级与二级链接、翻译链接名称，并选择适用市场。",
  "Article pages show these product cards automatically. FAQ entries appear on each selected product; leave the selection empty for a general FAQ.":
    "文章页面自动展示所选商品卡片。常见问题会出现在每个所选商品页面；不选商品则作为通用常见问题。",
  Assigned: "已分配",
  "Assigned permissions": "已分配权限",
  Assignment: "分配状态",
  "Associated products": "关联商品",
  "Attributes: key | label | text/number/boolean | required":
    "属性格式：键名 | 标签 | text/number/boolean | required",
  "Audit log": "审计日志",
  "Authenticator code": "认证器动态验证码",
  "Authenticator code for sensitive changes": "敏感操作的认证器验证码",
  "Authenticator recovery reason (super administrator)":
    "认证器恢复原因（超级管理员）",
  "Authenticator setup key": "认证器绑定密钥",
  Author: "作者",
  "Authorized preview ·": "授权预览 ·",
  Available: "可用",
  "Available stock": "可用库存",
  "Available stock for {value1}": "{value1} 的可用库存",
  "Available to sell after reservations": "扣除预留后的可售数量",
  "Available units": "可用数量",
  "Average out of five": "平均评分（满分 5 分）",
  "Awaiting verification": "等待邮箱验证",
  B2B: "企业采购",
  "B2B Sales | WEMOVE Admin": "企业销售 | WEMOVE 管理后台",
  "B2B cents": "批发价（最小货币单位）",
  Backorder: "缺货订购",
  Barcode: "条形码",
  "Base language": "原始语言",
  Before: "变更前",
  "Body text": "正文",
  "Brand and contact": "品牌与联系方式",
  "Build pages with content blocks, schedule publishing, and manage complete translations.":
    "使用内容模块搭建页面、安排发布时间，并管理完整译文。",
  "Bulk catalog & stock import": "批量导入商品与库存",
  "CMS Pages | WEMOVE Admin": "内容页面 | WEMOVE 管理后台",
  "CSV columns: slug, name, sku, msrpCents, available, status, categorySlug, tags. Separate tags with |. Blank category/tags cells clear those values; omit either column to preserve it. Export, edit and upload to review changes before applying them.":
    "CSV 列：slug、name、sku、msrpCents、available、status、categorySlug、tags。标签用 | 分隔。分类或标签单元格留空会清除原值；省略对应列则保留原值。可先导出、编辑并上传，审核变更后再应用。",
  "CSV columns: source,destination,status. Review up to 500 rows before saving; invalid paths and cycles reject the entire import.":
    "CSV 列：source、destination、status。保存前可审核最多 500 行；路径无效或存在循环时整批导入将被拒绝。",
  "CSV includes all matching requests and omits customer emails, names, messages and internal notes.":
    "CSV 包含全部符合筛选条件的请求，不包含客户邮箱、姓名、消息正文和内部备注。",
  Cancel: "取消",
  Category: "分类",
  "Category attribute templates": "分类属性模板",
  "Category pages": "分类页面",
  Center: "居中",
  "Change reason": "变更原因",
  "Change {value1} from {value2} to {value3}?":
    "将 {value1} 的状态从 {value2} 改为 {value3}？",
  "Choose the message and language, edit its content, and preview it with sample values. Transactional messages remain active when a customer opts out of marketing.":
    "选择消息类型与语言后编辑内容，并使用示例值预览。客户取消营销订阅后，交易相关通知仍会正常发送。",
  "Clear category": "清除分类",
  "Clear filters": "清除筛选",
  "Clear tags": "清除标签",
  Closed: "已关闭",
  Code: "代码",
  "Code / market": "代码 / 市场",
  "Common variables:": "通用变量：",
  "Completion removes profile, addresses, favorites, subscriptions, support message personal data and access. Unapproved applications are withdrawn; approved company and order records are retained. Active orders or company membership block completion.":
    "完成后将删除个人资料、地址、收藏、订阅、客服消息中的个人信息及账号访问权限。未批准的申请将撤回；已批准的企业和订单记录将保留。存在进行中的订单或企业成员关系时无法完成。",
  "Configured payment provider": "已配置的支付服务",
  "Configured rates": "已配置费率",
  "Configured region rates": "已配置地区税率",
  "Connected live carrier rates": "已接入的实时承运商运费",
  "Connected tax provider": "已接入的税务服务",
  Contact: "联系",
  "Contact Inbox | WEMOVE Admin": "联系收件箱 | WEMOVE 管理后台",
  "Contact inbox": "联系收件箱",
  "Contact pages": "联系页面",
  "Content checks": "内容检查",
  "Content preview": "内容预览",
  "Content studio": "内容管理",
  "Content type": "内容类型",
  Continue: "继续",
  Count: "数量",
  "Cover image URL": "封面图片网址",
  "Cover image description": "封面图片说明",
  "Create a new category": "创建分类",
  "Create an assisted customer order": "代客户创建订单",
  "Create category": "创建分类",
  "Create product": "创建商品",
  "Create role": "创建角色",
  "Create rule": "创建规则",
  "Create staff account": "创建员工账号",
  "Create unpaid order": "创建待付款订单",
  Currency: "币种",
  "Current MFA code": "当前动态验证码",
  "Current catalog prices, stock, tax and shipping rules apply. The customer completes payment from their account; their existing cart is preserved.":
    "使用当前商品价格、库存、税费与运费规则。客户需在自己的账号中完成付款，现有购物车保持不变。",
  Customer: "客户",
  "Customer accounts": "客户账号",
  "Customer messages, assignments and handling history.":
    "查看客户消息、任务分配和处理记录。",
  DEALER_ONLY: "仅经销商",
  DISABLED: "已禁用",
  DRAFT: "草稿",
  Dashboard: "工作台",
  "Dashboard metrics": "工作台指标",
  "Dealer Applications | WEMOVE Admin": "经销商申请 | WEMOVE 管理后台",
  "Dealer applications": "经销商申请",
  "Dealer price rules": "经销商价格规则",
  Decision: "审核决定",
  "Decorative image (empty alt is intentional)":
    "装饰图片（有意不填写替代文字）",
  "Default product sort": "默认商品排序",
  Delete: "删除",
  "Delete account personal data": "删除账号个人信息",
  Delivery: "配送",
  "Delivery worker enabled": "投递任务已启用",
  "Delivery worker paused": "投递任务已暂停",
  "Demo (no money charged)": "演示模式（不会实际扣款）",
  Deny: "拒绝",
  Description: "描述",
  Destination: "目标地址",
  "Destination path": "目标路径",
  Discount: "优惠",
  "Discount codes": "优惠码",
  "Display order": "显示顺序",
  "Display order (smaller first)": "显示顺序（较小值优先）",
  "Do not publish that language version": "不发布该语言版本",
  Download: "下载",
  "Download report CSV": "下载 CSV 报表",
  "Drag row to reorder": "拖动行调整顺序",
  "Duplicate as draft": "复制为草稿",
  "Duplicate title": "标题重复",
  EXPRESS: "加急配送",
  "Each SKU also needs an explicit quantity limit and dispatch estimate.":
    "每个 SKU 还需设置明确的数量限制与预计发货时间。",
  Edit: "编辑",
  "Edit category": "编辑分类",
  "Edit content": "编辑内容",
  "Edit language": "编辑语言",
  "Edit structured fields, publish windows, media and market prices. Copies start as drafts with zero inventory.":
    "编辑结构化字段、发布时段、媒体和市场价格。复制的商品初始为草稿，库存为零。",
  Email: "电子邮箱",
  "Email deliveries": "邮件投递",
  "Email offers:": "优惠邮件：",
  "Email verification": "邮箱验证",
  "Email verified": "邮箱已验证",
  "Enable Chinese": "启用中文",
  "Enable analytics after visitor consent": "访客同意后启用分析",
  "Ends at": "结束时间",
  "English is the default. Publish complete content translations before enabling another language.":
    "默认为英语。启用其他语言前，请先发布完整的内容译文。",
  "English label": "英文标签",
  "Enter one address per line. Groups receive separate operational notifications with management links. Verification and invitation credentials stay in the recipient’s own message.":
    "每行输入一个邮箱。各组会收到独立的运营通知与管理链接；验证和邀请凭证仅发送给对应收件人。",
  "Enter the current code from your authenticator.":
    "请输入认证器中当前显示的验证码。",
  "Estimated dispatch days": "预计发货天数",
  "Exclude from search engines": "不允许搜索引擎收录",
  "Exclude this language page from search engines":
    "不允许搜索引擎收录此语言页面",
  "Export CSV": "导出 CSV",
  "Export filtered CSV": "导出筛选结果 CSV",
  "Export filtered orders": "导出筛选订单",
  "FAQ (question | answer, one per line)": "常见问题（问题 | 答案，每行一组）",
  Featured: "精选优先",
  File: "文件",
  "Filter audit action": "筛选审计操作",
  "Filterable fields": "可筛选字段",
  "Find products": "查找商品",
  "Free shipping": "免运费",
  "Gallery order & accessible descriptions": "图库顺序与无障碍说明",
  Grant: "授予",
  "HTML message": "HTML 格式消息",
  "I confirm these values match authentic reviews for this product from the stated source.":
    "我确认这些数值与所填来源中该商品的真实评价一致。",
  INTERNAL: "仅内部",
  "Image or video URL": "图片或视频网址",
  Import: "导入",
  "Import redirects": "导入重定向",
  "In progress": "进行中",
  "Incomplete translations": "译文不完整时",
  "Individual permission overrides (super administrator)":
    "个人权限覆盖（超级管理员）",
  "Initial password": "初始密码",
  "Internal notification groups": "内部通知组",
  "Internal recipient groups": "内部收件人组",
  "Inventory alerts (": "库存预警（",
  "Inventory source": "库存来源",
  "Inventory source & low stock policy": "库存来源与低库存策略",
  "Inventory visibility": "库存显示方式",
  "JPG, PNG, WebP, PDF, MP4 or WebM, up to 50 MB.":
    "支持 JPG、PNG、WebP、PDF、MP4 或 WebM，最大 50 MB。",
  KB: "KB",
  "KB ·": "KB ·",
  "Keep current": "保留当前值",
  Language: "语言",
  "Language (blank = all)": "语言（留空表示全部）",
  "Language code": "语言代码",
  Languages: "语言设置",
  Left: "左对齐",
  "List items (one per line)": "列表项（每行一项）",
  "Live content and support metrics, with direct access to operational workbenches.":
    "查看最新内容与客服指标，并直接进入各运营工作台。",
  "Load staff administration": "加载员工管理",
  "Loading orders…": "正在加载订单…",
  "Loading products…": "正在加载商品…",
  "Loading requests…": "正在加载请求…",
  "Loading your workbench access…": "正在加载工作台权限…",
  "Loading…": "正在加载…",
  "Local URL": "站内网址",
  "Low stock threshold": "低库存阈值",
  "MFA code": "动态验证码",
  MOQ: "最小起订量",
  MSRP: "建议零售价",
  "MSRP cents": "建议零售价（最小货币单位）",
  "Manage dealer company": "管理经销商企业",
  "Manage multilingual email templates": "管理多语言邮件模板",
  "Manage publish status, retail/wholesale prices and available stock.":
    "管理发布状态、零售与批发价格，以及可用库存。",
  "Manually selected articles (up to 24; blank uses the category rule)":
    "手动选择文章（最多 24 篇；留空则按分类规则展示）",
  Market: "市场",
  "Market (ALL or market code)": "市场（ALL 或市场代码）",
  "Market (blank = all)": "市场（留空表示全部）",
  "Market allocations also consume the global stock pool. The marketplace must allow advance orders. Unfilled backorders cannot ship until stock is replenished. Create new market allocations when global reservations are zero.":
    "市场库存分配也会占用全局库存池。市场需允许提前订购；缺货订单需补货后才能发货。仅当全局预留量为零时可创建新的市场库存分配。",
  "Market code": "市场代码",
  "Market configuration": "市场配置",
  "Market tax and delivery rates are configurable commercial rules. Confirm production tax treatment and payment provider settings before opening retail.":
    "市场税率与运费可按商业规则配置。开放零售前请确认生产环境税务处理与支付服务设置。",
  "Markets (comma separated; blank = all)":
    "市场（用英文逗号分隔；留空表示全部）",
  "Markets, currencies and checkout settings": "市场、币种与结账设置",
  "Maximum advance order units": "提前订购数量上限",
  "Media library": "媒体库",
  "Media | WEMOVE Admin": "媒体库 | WEMOVE 管理后台",
  Message: "消息",
  "Metadata, access & version replacement": "元信息、访问权限与版本替换",
  "Missing description": "缺少描述",
  "Module enabled": "启用模块",
  "Module ends at (UTC)": "模块结束时间（UTC）",
  "Module starts at (UTC)": "模块开始时间（UTC）",
  "Move associated product {value1} up": "上移第 {value1} 个关联商品",
  "Move block {value1} up": "上移第 {value1} 个模块",
  "Move block {value1} down": "下移第 {value1} 个模块",
  "Move media {value1} earlier": "前移第 {value1} 个媒体",
  "Move navigation {value1} up": "上移第 {value1} 个导航项",
  "Move secondary navigation {value1} up": "上移第 {value1} 个二级导航项",
  "Move selected article {value1} up": "上移第 {value1} 篇已选文章",
  "Move {value1} from {value2} to {value3}?":
    "将 {value1} 从 {value2} 改为 {value3}？",
  "My security": "账号安全",
  Name: "名称",
  Navigation: "导航",
  "New SKU prefix": "新 SKU 前缀",
  "New copy slug": "副本网址标识",
  "New discount code": "新建优惠码",
  "New market": "新建市场",
  "New market allocation": "新建市场库存分配",
  "New page": "新建页面",
  "New price rule": "新建价格规则",
  Newest: "最新优先",
  Newsletter: "邮件订阅",
  Next: "下一页",
  "No applications found.": "未找到申请。",
  "No category": "不设置分类",
  "No country": "未填写国家或地区",
  "No display name": "未填写显示名称",
  "No matching activity in this period.": "本时段没有符合条件的活动记录。",
  "No matching products.": "没有符合条件的商品。",
  "No operational permissions are assigned. Contact an administrator if you need additional access.":
    "尚未分配运营权限。如需更多访问权限，请联系管理员。",
  "No orders found.": "未找到订单。",
  "No orders.": "暂无订单。",
  "No phone": "未填写电话",
  "No requests match these filters.": "没有符合筛选条件的请求。",
  "No requests.": "暂无请求。",
  "No saved addresses.": "暂无已保存的地址。",
  "No team": "未分配团队",
  "Not recorded": "未记录",
  "Not started": "未开始",
  "Not subscribed": "未订阅",
  "Note:": "备注：",
  "Notification templates": "通知模板",
  "Number of cards": "卡片数量",
  "Number of reviews": "评价数量",
  "Old path": "原路径",
  "One group per line: preferred phrase = alternative, alternative":
    "每行一组：首选词 = 同义词, 同义词",
  Open: "已开放",
  "Open authenticator": "打开认证器",
  "Operations console — authorized staff only.":
    "运营管理平台，仅限已授权员工访问。",
  "Operations dashboard": "运营工作台",
  "Optional HTML message": "HTML 消息（选填）",
  "Order fulfillment": "订单履约",
  "Order operations": "订单管理",
  "Orders | WEMOVE Admin": "订单 | WEMOVE 管理后台",
  PUBLIC: "公开",
  Page: "页",
  "Page title": "页面标题",
  "Parent category": "上级分类",
  Password: "密码",
  Pause: "暂停",
  Paused: "已暂停",
  "Payment mode": "支付模式",
  "Payments, shipments & returns": "付款、发货与退货",
  "Pending files are unavailable for download. Cleanup retries automatically after temporary storage failures.":
    "待清理文件无法下载。临时存储故障恢复后会自动重试清理。",
  "Permanently delete “{value1}”?": "永久删除“{value1}”？",
  "Permission changes take effect on the next API request. SUPER_ADMIN always has full access.":
    "权限变更在下一次接口请求时生效。超级管理员始终拥有全部权限。",
  Permissions: "权限",
  "Plain text message": "纯文本消息",
  "Platform settings and delivery queue": "平台设置与投递队列",
  "Policy consent": "政策同意记录",
  Preferences: "偏好设置",
  Preorder: "预售",
  Preview: "预览",
  "Preview current draft": "预览当前草稿",
  "Preview formatting": "预览格式",
  "Preview unavailable": "暂时无法预览",
  "Preview without sending": "仅预览，不发送",
  Previous: "上一页",
  Price: "价格",
  "Price (minor units)": "价格（最小货币单位）",
  "Price change history": "价格变更记录",
  "Prices & markets": "价格与市场",
  "Prices, promotions & markets": "价格、优惠与市场",
  Priority: "优先级",
  "Privacy attachment cleanup": "隐私附件清理",
  "Privacy requests": "隐私请求",
  "Private qualifications": "私密资质文件",
  Product: "商品",
  "Product content & merchandising": "商品内容与展示管理",
  "Product name": "商品名称",
  "Product name or slug": "商品名称或网址标识",
  "Product rating display": "商品评分展示",
  "Product translations": "商品译文",
  "Products & SKUs": "商品与 SKU",
  "Products | WEMOVE Admin": "商品 | WEMOVE 管理后台",
  Profile: "个人资料",
  "Profile, addresses and orders": "个人资料、地址与订单",
  "Public images missing alt text:": "缺少替代文字的公开图片：",
  "Publication date (UTC)": "发布日期（UTC）",
  "Publication status": "发布状态",
  "Publish a complete translation of the name, summary, source descriptions, specifications and FAQ. Save source specification or FAQ changes before updating their translations. Enable the language in site settings when it is ready for visitors.":
    "请发布名称、摘要、原始说明、规格和常见问题的完整译文。更新规格或常见问题译文前，先保存对应原文。内容就绪后可在站点设置中启用该语言。",
  "Publish at": "发布时间",
  "Publish at (UTC)": "发布时间（UTC）",
  "Publish complete translation": "发布完整译文",
  "Publish state": "发布状态",
  Quantity: "数量",
  "RBAC and MFA are enforced by the API.":
    "后台强制执行角色权限验证与双重身份验证。",
  REGISTERED: "仅注册用户",
  Rate: "费率",
  "Re-scan file": "重新扫描文件",
  "Ready for publication": "待发布",
  "Reason for account access change (at least 5 characters)":
    "账号访问权限变更原因（至少 5 个字符）",
  "Reason for assisted order": "代客下单原因",
  "Recent 404 pages": "最近的 404 页面",
  "Recent orders (up to 100)": "近期订单（最多 100 条）",
  "Recover authenticator": "恢复认证器",
  Redemptions: "兑换次数",
  "Redirect CSV": "重定向 CSV",
  Redirects: "重定向",
  "Regional tax overrides": "地区税率覆盖",
  "Registration:": "注册：",
  Reject: "拒绝",
  "Reject with explanation": "填写原因并拒绝",
  Remove: "移除",
  "Remove link": "移除链接",
  "Remove override": "移除覆盖规则",
  "Remove rate": "移除费率",
  "Remove secondary link": "移除二级链接",
  "Rendered HTML source": "渲染后的 HTML 源码",
  "Replacement password": "新密码",
  "Replaces media ID (upload new file first)":
    "被替换媒体 ID（请先上传新文件）",
  Reports: "报表",
  "Request more info": "要求补充资料",
  Reserved: "已预留",
  "Reset MFA and revoke sessions": "重置双重验证并撤销会话",
  "Reset password and revoke sessions": "重置密码并撤销会话",
  "Resolution / retention explanation": "处理结果 / 保留说明",
  "Resolve request": "处理请求",
  "Resource title": "资源标题",
  "Resource type": "资源类型",
  "Restore as draft": "恢复为草稿",
  "Retail enabled": "启用零售",
  Retry: "重试",
  "Review note (required for more info or rejection)":
    "审核备注（要求补充资料或拒绝时必填）",
  "Review qualifications with auditable state transitions.":
    "审核资质并记录可追溯的状态变更。",
  "Review source": "评价来源",
  Right: "右对齐",
  Roles: "角色",
  "Roles and permissions": "角色与权限",
  "SEO and social sharing": "搜索优化与社交分享",
  SKU: "SKU",
  "SKU market prices & barcodes": "SKU 市场价格与条形码",
  "SMTP configured": "SMTP 已配置",
  "SMTP pending configuration": "SMTP 尚待配置",
  STANDARD: "标准配送",
  Sale: "销售价",
  "Sale cents": "销售价（最小货币单位）",
  "Sale price (optional)": "销售价（选填）",
  "Sample recipient": "示例收件人",
  "Sample variables (JSON)": "示例变量（JSON）",
  "Save analytics": "保存分析设置",
  "Save brand": "保存品牌设置",
  "Save category": "保存分类",
  "Save category template": "保存分类模板",
  "Save code": "保存优惠码",
  "Save content": "保存内容",
  "Save inventory policy": "保存库存策略",
  "Save languages": "保存语言设置",
  "Save market": "保存市场",
  "Save market inventory": "保存市场库存",
  "Save market price": "保存市场价格",
  "Save metadata & grants": "保存元信息与授权",
  "Save navigation": "保存导航",
  "Save overrides": "保存覆盖规则",
  "Save permissions": "保存权限",
  "Save price rule": "保存价格规则",
  "Save product content": "保存商品内容",
  "Save purchase policy": "保存采购策略",
  "Save rating display": "保存评分展示",
  "Save recipient groups": "保存收件人组",
  "Save recipients": "保存收件人",
  "Save redirect": "保存重定向",
  "Save staff": "保存员工",
  "Save synonyms": "保存同义词",
  "Save templates": "保存模板",
  "Saving…": "正在保存…",
  Scope: "范围",
  "Search and social metadata": "搜索与社交元信息",
  "Search customers": "搜索客户",
  "Search name, email or message": "搜索姓名、邮箱或消息",
  "Search phrases": "搜索词",
  "Search staff": "搜索员工",
  "Search synonyms": "搜索同义词",
  "Search title, filename, language or tags": "搜索标题、文件名、语言或标签",
  "Search visibility": "搜索可见性",
  "Second button URL": "第二个按钮网址",
  "Second button label": "第二个按钮文字",
  "Security settings": "安全设置",
  "Select SKU": "选择 SKU",
  "Select a company from the B2B workbench.": "请从企业采购工作台选择企业。",
  "Select customer": "选择客户",
  "Select product": "选择商品",
  "Selected product IDs (comma separated)": "所选商品 ID（用英文逗号分隔）",
  "Selection rule": "选择规则",
  "Send password reset email": "发送密码重置邮件",
  "Sender:": "发件人：",
  "Set up an authenticator before entering the administration area. Add this key to your authenticator, then enter its six-digit code.":
    "进入管理后台前需绑定认证器。请将此密钥添加到认证器，然后输入其中显示的六位验证码。",
  "Setup, how to play, care & safety": "安装、玩法、保养与安全说明",
  "Shipping calculation": "运费计算",
  "Show category": "显示分类",
  "Show the aggregate rating on this product page": "在此商品页展示汇总评分",
  "Show the complete English page": "显示完整英文页面",
  "Sign in": "登录",
  "Sign out": "退出登录",
  "Site settings": "站点设置",
  Slug: "网址标识",
  Source: "来源",
  "Source FAQ:": "原始常见问题：",
  "Source error (blank = healthy)": "来源错误（留空表示正常）",
  "Source sync failure (blank = healthy)": "来源同步故障（留空表示正常）",
  "Source synchronization failed — checkout blocked":
    "来源同步失败，已暂停结账",
  "Source:": "来源：",
  "Specification table (name = value, one per line)":
    "规格表（名称 = 值，每行一项）",
  "Staff accounts": "员工账号",
  "Staff email": "员工邮箱",
  "Staff page": "员工列表页",
  "Start again": "重新开始",
  "Start review": "开始审核",
  "Starts at": "开始时间",
  "State / region": "州 / 地区",
  Status: "状态",
  "Status for {value1}": "{value1} 的状态",
  "Stock updated for {value1}.": "已更新 {value1} 的库存。",
  "Stop new purchases": "停止新采购",
  Subject: "主题",
  Submitted: "已提交",
  Suspend: "停用",
  Tags: "标签",
  "Tags (comma separated)": "标签（用英文逗号分隔）",
  "Tax calculation": "税费计算",
  "Tax rate %": "税率 %",
  Team: "团队",
  "Text alignment": "文字对齐",
  "Text formatting": "文字格式",
  "This is an optional aggregate of existing reviews. Enter a real source and its actual five-point average and count. The default is hidden; empty review sets are never presented as a rating.":
    "此功能可选，用于汇总现有评价。请填写真实来源、实际的五星制平均分和评价数量。默认隐藏；没有评价时不展示评分。",
  "Top-level category": "顶级分类",
  "Track payment, partial shipments, returns and inventory reservations.":
    "跟踪付款、分批发货、退货与库存预留。",
  "Translated answer": "译文答案",
  "Translated label": "译文标签",
  "Translated question": "译文问题",
  "Translated value": "译文内容",
  "Translation status": "翻译状态",
  Type: "类型",
  US: "美国",
  Unassigned: "未分配",
  Uncategorized: "未分类",
  "Unpublish at": "下线时间",
  "Unpublish at (UTC)": "下线时间（UTC）",
  Upload: "上传",
  "Upload CSV": "上传 CSV",
  Uploaded: "已上传",
  "Use two or three lowercase letters, optionally followed by a region such as pt-BR. Account and checkout interfaces support English and Chinese.":
    "使用两到三个小写字母，可追加地区代码，例如 pt-BR。账户与结账界面支持中英文。",
  "Users and staff": "用户与员工",
  "Valid from": "生效时间",
  "Valid until": "失效时间",
  "Variant / scope": "款式 / 范围",
  "Variant media (URL | alt text | image/video | language | market)":
    "款式媒体（网址 | 替代文字 | image/video | 语言 | 市场）",
  "Variant name": "款式名称",
  "Variant specifications (name = value)": "款式规格（名称 = 值）",
  "Verified identity / recovery reason": "已核实身份 / 恢复原因",
  "Verified review provider or source record": "已核实的评价平台或来源记录",
  "Verify and sign in": "验证并登录",
  "Verifying…": "正在验证…",
  Version: "版本",
  "Version history": "版本记录",
  Visibility: "可见范围",
  "Visitors may dismiss this announcement": "访客可关闭此公告",
  "WEMOVE ADMIN": "WEMOVE 管理后台",
  "WEMOVE Admin": "WEMOVE 管理后台",
  "Weight and order amount delivery rates": "按重量与订单金额计算运费",
  "When available stock reaches zero": "可用库存为零时",
  Window: "有效时段",
  Workbenches: "工作台",
  "Your role does not include dashboard reporting. Available workbenches are listed below.":
    "您的角色没有工作台报表权限。下方列出了可访问的工作台。",
  by: "上传者",
  customers: "位客户",
  "days. Business state counts: current totals. Financial amounts are shown only with financial report permission.":
    "天。业务状态统计为当前总数；仅有财务报表权限的用户可查看财务金额。",
  "en, zh, fr, de, zh-CN": "en, zh, fr, de, zh-CN",
  enabled: "已启用",
  errors: "处错误",
  "fr, de, pt-BR": "fr, de, pt-BR",
  image: "图片",
  label: "标签",
  "legacy file": "旧版文件",
  "matching events": "条匹配事件",
  "new SKUs ·": "个新 SKU ·",
  no: "否",
  off: "关闭",
  "product-slug": "商品网址标识（小写英文）",
  redirects: "条重定向",
  reserved: "已预留",
  results: "条结果",
  rows: "行",
  staff: "员工",
  translation: "译文",
  unlimited: "不限",
  "updates ·": "项更新 ·",
  v: "版本",
  video: "视频",
  yes: "是",
  "zh, fr, de, zh-CN": "zh, fr, de, zh-CN",
  "{value1} available / threshold {value2}":
    "可用 {value1} 件 / 预警阈值 {value2}",
  "{value1} matching requests · Page {value2} of {value3}":
    "共 {value1} 条匹配请求 · 第 {value2} 页，共 {value3} 页",
  "{value1} redirects saved.": "已保存 {value1} 条重定向。",
  "{value1} reserved{value2}": "已预留 {value1} 件{value2}",
  "{{name}}, {{email}}, {{subject}}, {{text}}, {{link}}, {{kind}}":
    "{{name}}, {{email}}, {{subject}}, {{text}}, {{link}}, {{kind}}",
  "· Default language:": "· 默认语言：",
  "· MFA": "· 双重验证",
  "· Market allocation & advance orders": "· 市场库存分配与提前订购",
  "· Published": "· 发布时间",
  "· Reserved:": "· 已预留：",
  "· SHA-256": "· SHA-256",
  "· Version": "· 版本",
  "· attempts": "· 尝试次数",
  "A password reset email was requested. The customer chooses their own new password.":
    "已申请发送密码重置邮件，客户可自行设置新密码。",
  ACCESSORY: "配件",
  ALL: "全部",
  APPROVED: "已批准",
  ARTICLE: "文章",
  ASSIGNED: "已分配",
  "Accessory product slugs": "配件商品网址标识",
  "Account data was anonymized. Private attachment erasure is queued for retry and access is blocked.":
    "账号数据已匿名化。私密附件已禁止访问，删除任务正在排队重试。",
  "Account data was anonymized. Some files remain referenced by other business records; review their retention in the media workbench.":
    "账号数据已匿名化。部分文件仍被其他业务记录引用，请在媒体工作台核查其保留情况。",
  "Address line 1": "详细地址",
  "Address line 2": "补充地址",
  "Age & supervision guidance": "适用年龄与监护说明",
  "Age and safety guidance": "适用年龄与安全说明",
  "An access-change reason of at least 5 characters is required.":
    "请填写至少 5 个字符的访问权限变更原因。",
  Approved: "已批准",
  "Archive redirect path": "归档后的重定向路径",
  Attempts: "尝试次数",
  "Audit trail": "审计记录",
  "B2B quotes & purchase orders": "企业报价与采购单",
  B2B_DEFAULT: "默认批发价",
  BACKORDER: "缺货订购",
  BANNER: "横幅公告",
  Bold: "加粗",
  Bullet: "项目符号",
  "Button label": "按钮文字",
  CANCELLED: "已取消",
  CATALOG: "产品目录",
  CERTIFICATE: "认证证书",
  CLOSED: "已关闭",
  "CMS pages": "内容页面",
  COMPANY_SPECIFIC: "企业专属",
  COMPLETED: "已完成",
  CONFIGURED: "已配置",
  CONFIRMED: "已确认",
  CONTACT: "联系表单",
  "CSV contains an unclosed quote": "CSV 存在未闭合的引号。",
  "CSV exceeds 600 KB.": "CSV 文件不能超过 600 KB。",
  "CSV must be under 2 MB": "CSV 文件必须小于 2 MB。",
  "Canonical URL": "规范网址",
  "Category saved. Active categories are available in the storefront.":
    "分类已保存。已启用的分类可在商城查看。",
  "Changes saved.": "变更已保存。",
  "Choose between 1 and 500 rows.": "请选择 1 至 500 行。",
  City: "城市",
  "Company / book / tier ID": "企业 / 价目表 / 等级 ID",
  "Confirm the aggregate comes from authentic reviews.":
    "请确认汇总数据来自真实评价。",
  "Consented field performance": "已获同意的实际访问性能",
  "Contact messages": "联系消息",
  Content: "内容",
  "Content saved. Published changes are visible on the website.":
    "内容已保存。已发布的变更可在网站查看。",
  "Could not load customer": "无法加载客户信息。",
  "Country code": "国家或地区代码",
  Created: "创建时间",
  "Customer & staff accounts": "客户与员工账号",
  DEAD: "投递失败",
  DEALER_SUPPORT: "经销商支持",
  DEFAULT: "默认",
  DEMO: "演示",
  "Dealer review": "经销商审核",
  Dealers: "经销商",
  "Delete failed.": "删除失败。",
  "Delivery fee": "配送费",
  "Desktop image URL": "桌面端图片网址",
  "Discount %": "折扣百分比",
  EXACT: "显示准确库存",
  "Each specification must have a name = value":
    "每项规格需按“名称 = 值”的格式填写。",
  "Eligible customer IDs (blank = all)": "适用客户 ID（留空表示全部）",
  "Eligible product IDs (comma separated; blank = all)":
    "适用商品 ID（用英文逗号分隔；留空表示全部）",
  "Enter a language code such as zh, fr, de or zh-CN. Edit English in the source fields.":
    "请输入 zh、fr、de 或 zh-CN 等语言代码。英文请在原始内容字段中编辑。",
  "Enter the current 6-digit MFA code before exporting.":
    "导出前请输入当前六位动态验证码。",
  "Enter the current 6-digit MFA code before reviewing.":
    "审核前请输入当前六位动态验证码。",
  "Enter the current 6-digit MFA code before saving changes.":
    "保存变更前请输入当前六位动态验证码。",
  "Enter the current 6-digit MFA code before updating an order.":
    "更新订单前请输入当前六位动态验证码。",
  "Enter the current 6-digit MFA code first.": "请先输入当前六位动态验证码。",
  "Enter the current 6-digit MFA code.": "请输入当前六位动态验证码。",
  "Enter the reason for this order status change.": "请填写订单状态变更原因。",
  "Enter your current MFA code above.": "请在上方输入当前动态验证码。",
  "Enter your current six-digit MFA code.": "请输入当前六位动态验证码。",
  "Exact available quantity": "显示准确可用数量",
  "Export failed.": "导出失败。",
  "Express delivery": "加急配送",
  FAQ: "常见问题",
  FORM: "表单",
  FULFILLED: "已履约",
  "Fixed discount amount": "固定优惠金额",
  "Free standard delivery above": "标准配送免运费门槛",
  HIDDEN: "已隐藏",
  HIDE: "隐藏",
  HIGH: "高",
  HOME: "首页",
  HTTP: "在线服务",
  "Hide stock display": "隐藏库存",
  IMAGE: "图片",
  IN_PROGRESS: "进行中",
  IN_STOCK_ONLY: "仅销售现货",
  "Image description": "图片说明",
  "Internal recipient groups saved.": "内部收件人组已保存。",
  "Inventory hold minutes": "库存预留时长（分钟）",
  Italic: "斜体",
  LEVEL: "库存级别",
  LOW: "低",
  Link: "链接",
  MANUAL: "说明书",
  MORE_INFO_REQUIRED: "待补充资料",
  "Market name": "市场名称",
  "Markets (blank = all)": "市场（留空表示全部）",
  "Maximum age": "最大适用年龄",
  "Maximum order amount": "最高订单金额",
  "Maximum total uses": "总使用次数上限",
  "Maximum uses per customer": "每位客户使用次数上限",
  "Maximum weight (g)": "最大重量（克）",
  "Media assets": "媒体资源",
  "Minimum age": "最小适用年龄",
  "Minimum order amount": "最低订单金额",
  "Minimum quantity": "最小数量",
  "Minimum weight (g)": "最小重量（克）",
  "Mobile image URL": "移动端图片网址",
  "More info required": "待补充资料",
  NAVIGATION: "导航",
  NEW: "新建",
  NORMAL: "普通",
  NOT_STARTED: "未开始",
  "No recorded price changes.": "暂无价格变更记录。",
  Notification: "通知",
  OPEN: "待处理",
  ORDER_SUPPORT: "订单支持",
  OTHER: "其他",
  "Operation failed": "操作失败，请稍后重试。",
  "Operations reports": "运营报表",
  Orders: "订单",
  PAGE: "普通页面",
  PAID: "已付款",
  PENDING: "待处理",
  PREORDER: "预售",
  PRICE_TABLE: "价目表",
  PRIVACY: "隐私请求",
  PRODUCT_INQUIRY: "商品咨询",
  PUBLISHED: "已发布",
  Phone: "电话",
  "Play guide": "玩法说明",
  "Postal code": "邮政编码",
  "Pricing & markets": "价格与市场",
  "Product created.": "商品已创建。",
  "Product status updated.": "商品状态已更新。",
  Products: "商品",
  "Products & stock": "商品与库存",
  "Published FAQs": "已发布常见问题",
  "Published articles": "已发布文章",
  READY: "待发布",
  REJECTED: "已拒绝",
  RELATED: "相关商品",
  REPLACEMENT: "替换配件",
  RESOLVED: "已解决",
  "Rating display saved.": "评分展示已保存。",
  Recipient: "收件人",
  "Redirect saved.": "重定向已保存。",
  Region: "地区",
  Rejected: "已拒绝",
  "Related product slugs": "相关商品网址标识",
  "Replacement part slugs": "替换配件网址标识",
  "Report download failed. Check your permission and MFA code.":
    "报表下载失败，请检查权限与动态验证码。",
  "Required columns: slug, name, sku, msrpCents, available, status":
    "必需列：slug、name、sku、msrpCents、available、status。",
  "Reset request failed": "重置申请失败。",
  "Review failed.": "审核失败。",
  "Roles & permissions": "角色与权限",
  SCHEDULED: "已排期",
  "SEO & redirects": "搜索优化与重定向",
  "SKU created with its initial stock.": "SKU 及其初始库存已创建。",
  STATUS: "仅显示状态",
  SUBMITTED: "已提交",
  SUPER_ADMIN: "超级管理员",
  SUSPENDED: "已停用",
  Sales: "销售",
  "Sample business details": "示例业务详情",
  "Sample notification": "示例通知",
  "Saved.": "已保存。",
  "Scenes (comma separated)": "使用场景（用英文逗号分隔）",
  Search: "搜索",
  "Search description": "搜索描述",
  "Search title": "搜索标题",
  Security: "安全",
  "Settings saved.": "设置已保存。",
  "Sign in failed.": "登录失败。",
  Skills: "能力培养",
  "Social description": "社交分享描述",
  "Social image URL": "社交分享图片网址",
  "Social title": "社交分享标题",
  "Standard delivery": "标准配送",
  "Status only": "仅显示状态",
  "Stock levels": "库存级别",
  Summary: "摘要",
  "Support leads": "客服线索",
  "Supported country codes": "支持的国家或地区代码",
  TIER_LEVEL: "经销商等级",
  "Templates saved. New and retried deliveries use these versions.":
    "模板已保存。新邮件与重试投递将使用此版本。",
  Text: "文字",
  "This language is already listed below.": "下方已存在此语言。",
  UNASSIGNED: "未分配",
  UNDER_REVIEW: "审核中",
  URGENT: "紧急",
  "URL slug": "网址标识",
  USD: "美元",
  "Unable to create SKU.": "无法创建 SKU。",
  "Unable to create download link.": "无法创建下载链接。",
  "Unable to create product.": "无法创建商品。",
  "Unable to export messages.": "无法导出消息。",
  "Unable to find products": "无法查找商品。",
  "Unable to load": "无法加载，请稍后重试。",
  "Unable to load applications.": "无法加载申请。",
  "Unable to load catalog.": "无法加载商品目录。",
  "Unable to load content": "无法加载内容。",
  "Unable to load media.": "无法加载媒体资源。",
  "Unable to load messages.": "无法加载消息。",
  "Unable to load orders.": "无法加载订单。",
  "Unable to load your access permissions.": "无法加载访问权限。",
  "Unable to open qualification file.": "无法打开资质文件。",
  "Unable to save": "无法保存，请稍后重试。",
  "Unable to save category": "无法保存分类。",
  "Unable to save redirect": "无法保存重定向。",
  "Unable to update order.": "无法更新订单。",
  "Unable to update product.": "无法更新商品。",
  "Unable to update status.": "无法更新状态。",
  "Unable to update stock.": "无法更新库存。",
  "Under review": "审核中",
  "Unit price": "单价",
  "United States": "美国",
  "Upload failed.": "上传失败。",
  VIDEO: "视频",
  "Variant ID": "款式 ID",
  "Version restored as draft.": "该版本已恢复为草稿。",
  "Video poster URL": "视频封面网址",
  WAITING_CUSTOMER: "等待客户回复",
  WEBHOOK: "外部回调",
  "{date} · Staff {staff}": "{date} · 员工 {staff}",
  hero: "主视觉",
  text: "正文",
  heading: "标题",
  list: "列表",
  quote: "引用",
  cta: "行动按钮",
  products: "商品",
  categories: "分类",
  articles: "文章",
  faq: "常见问题",
  download: "下载",
  newsletter: "邮件订阅",
  values: "品牌理念",
  title: "标题",
  description: "描述",
  category: "分类",
  tag: "标签",
  ogTitle: "社交分享标题",
  ogDescription: "社交分享描述",
  ogImage: "社交分享图片",
  canonical: "规范网址",
  name: "名称",
  logo: "品牌标志",
  favicon: "网站图标",
  primaryColor: "品牌主色",
  contactEmail: "联系邮箱",
  contactPhone: "联系电话",
  address: "地址",
  dealer: "经销商",
  support: "客户支持",
  orders: "订单",
  usageLocations: "使用位置",
  companyIds: "授权企业 ID",
  productIds: "关联商品 ID",
  featured: "精选优先",
  newest: "最新优先",
  "price-asc": "价格从低到高",
  "price-desc": "价格从高到低",
  events: "行为事件",
  leads: "联系线索",
  applications: "申请",
  pages: "页面",
  purchaseOrders: "企业采购单",
  mail: "邮件",
  views: "浏览次数",
  "add To Cart": "加入购物车数",
  purchases: "购买次数",
  inquiries: "询价次数",
  "search Clicks": "搜索点击次数",
  "out Of Stock Views": "缺货商品浏览次数",
  "add To Cart Rate": "加购率（%）",
  "purchase Rate": "购买率（%）",
  "inquiry Rate": "询价率（%）",
  path: "路径",
  reads: "阅读次数",
  "product Clicks": "商品点击次数",
  downloads: "下载次数",
  "assisted Sessions": "辅助转化会话数",
  query: "查询词",
  searches: "搜索次数",
  "no Results": "无结果次数",
  clicks: "点击次数",
  "converted Sessions": "转化会话数",
  channel: "渠道",
  market: "市场",
  currency: "币种",
  "paid Orders": "已付款订单数",
  "paid Cents": "实付金额（最小货币单位）",
  "average Paid Cents": "平均实付金额（最小货币单位）",
  "refunded Cents": "退款金额（最小货币单位）",
  "refund Rate": "退款率（%）",
  approved: "已批准数",
  "average Review Hours": "平均审核时长（小时）",
  "ordering Companies": "下单企业数",
  "repeat Companies": "复购企业数",
  "approval Rate": "批准率（%）",
  "repeat Rate": "复购率（%）",
  source: "来源",
  requests: "请求数",
  resolved: "已解决数",
  "average Response Hours": "平均响应时长（小时）",
  "resolution Rate": "解决率（%）",
  metric: "性能指标",
  device: "设备",
  samples: "样本数",
  p75: "第 75 百分位",
  mobile: "移动设备",
  desktop: "桌面设备",
  B2C: "零售",
  product: "商品",
  "Manage roles and permissions": "管理角色与权限",
  "Manage system settings": "管理系统设置",
  "Read customer accounts": "查看客户账号",
  "Manage customer accounts and privacy": "管理客户账号与隐私",
  "Read financial report amounts": "查看财务报表金额",
  "Read reports": "查看报表",
  "Read content": "查看内容",
  "Manage content": "管理内容",
  "Read media": "查看媒体",
  "Manage media": "管理媒体",
  "Read dealer operations": "查看经销商业务",
  "Manage dealer operations": "管理经销商业务",
  "Read customer support": "查看客户支持",
  "Manage customer support": "管理客户支持",
  "Product create": "创建商品",
  "Product edit": "编辑商品",
  "Product publish": "发布商品",
  "Product archive": "归档商品",
  "Product export": "导出商品",
  "Product import": "导入商品",
  "Read staff": "查看员工",
  "Manage staff and roles": "管理员工与角色",
  "Read audit logs": "查看审计日志",
  "Read products": "查看商品",
  "Manage products and variants": "管理商品与款式",
  "Manage price rules": "管理价格规则",
  "Manage CMS pages and home modules": "管理内容页面与首页模块",
  "Manage media assets": "管理媒体资源",
  "Manage contact leads": "处理联系线索",
  "Review dealer applications": "审核经销商申请",
  "Read dealer data": "查看经销商数据",
  "Manage RFQs and quotes": "处理询价与报价",
  "Read orders": "查看订单",
  "Fulfill orders and refunds": "订单履约与退款",
  "Super administrator": "超级管理员",
  "Catalog operations": "商品运营",
  "Customer support": "客户支持",
  "Content operations": "内容运营",
  "Dealer operations": "经销商运营",
  Administrator: "管理员",
  QUEUED: "排队中",
  SENDING: "发送中",
  SENT: "已发送",
  RETRY: "等待重试",
  CLEAN: "扫描通过",
  INFECTED: "检测到风险",
  FAILED: "失败",
  PROCESSING: "处理中",
  SHIPPED: "已发货",
  UNPAID: "待付款",
  PARTIALLY_PAID: "部分付款",
  PARTIALLY_REFUNDED: "部分退款",
  REFUNDED: "已退款",
  ENABLED: "已启用",
  OPTED_OUT: "已退订",
  SUBSCRIBED: "已订阅",
  UNSUBSCRIBED: "已退订",
  view_product: "浏览商品",
  add_to_cart: "加入购物车",
  remove_from_cart: "移出购物车",
  purchase: "购买",
  request_quote: "提交询价",
  search_click: "点击搜索结果",
  view_content: "阅读内容",
  cta_click: "点击行动按钮",
  download_asset: "下载资源",
  web_vital: "网页性能",
  newsletter_subscribe: "订阅邮件",
  contact_submit: "提交咨询",
  login: "登录",
  register: "注册",
  STAFF: "员工",
  USER: "用户",
  SYSTEM: "系统",
  "Business notification": "WEMOVE 业务通知",
  "Account welcome": "欢迎加入 WEMOVE",
  "Password changed": "您的密码已修改",
  "Account disabled": "您的账号已停用",
  "Account deletion requested": "已收到账号删除申请",
  "Privacy request resolved": "您的隐私申请有新进展",
  "New device sign-in": "您的账号出现新设备登录",
  "Dealer application confirmation": "已收到您的经销商申请",
  "Claim dealer application": "认领您的经销商申请",
  "Dealer application resubmitted": "您的补充材料已提交",
  "Dealer application review": "您的经销商申请审核有新进展",
  "Company team invitation": "您收到企业团队邀请",
  "Company membership disabled": "您的企业成员权限已停用",
  "RFQ submitted": "已收到您的报价请求",
  "Quote ready": "您的企业报价已准备好",
  "Quote expiring": "您的企业报价即将到期",
  "Quote accepted": "您已接受企业报价",
  "Quote rejected": "您的企业报价已拒绝",
  "Sales RFQ notification": "有新的企业报价请求",
  "Purchase order confirmed": "您的企业采购单已确认",
  "Assisted purchase order created": "平台已为您的企业建立采购单",
  "Purchase order processing": "您的企业采购单正在处理",
  "Purchase order completed": "您的企业采购单已完成",
  "Purchase order adjusted": "您的企业采购单信息已调整",
  "Purchase order payment updated": "您的企业采购单付款状态已更新",
  "Purchase order shipped": "您的企业采购单已发货",
  "Purchase order cancelled": "您的企业采购单已取消",
  "Business return requested": "已收到您的企业退货申请",
  "Business return approved": "您的企业退货申请已批准",
  "Business return rejected": "您的企业退货申请未通过",
  "Business return tracking updated": "您的企业退货物流已更新",
  "Business return withdrawn": "您的企业退货申请已撤回",
  "Business return received": "您的企业退货已验收",
  "Business refund requested": "已收到您的企业退款申请",
  "Business refund reviewed": "您的企业退款申请已审核",
  "Business refund withdrawn": "您的企业退款申请已撤回",
  "Business refund completed": "您的企业退款已确认完成",
  "Retail order created": "您的订单已创建",
  "Assisted retail order created": "您的订单已创建",
  "Retail payment updated": "您的订单付款状态已更新",
  "Retail shipment updated": "您的订单发货状态已更新",
  "Retail refund processed": "您的订单退款已处理",
  "Retail return updated": "您的售后申请已更新",
  "Exchange shipped": "您的换货商品已发出",
  "Retail order status updated": "您的订单状态已更新",
  "Retail order cancelled": "您的订单已取消",
  "Retail order expired": "您的订单已超时关闭",
  "Retail refund updated": "您的订单退款状态已更新",
  "Contact request received": "已收到您的 WEMOVE 咨询",
  "Contact reply": "您的 WEMOVE 咨询有新回复",
  "Contact request status updated": "您的 WEMOVE 咨询状态已更新",
  "Confirm newsletter subscription": "请确认您的 WEMOVE 邮件订阅",
  "Newsletter unsubscribed": "您已取消 WEMOVE 营销邮件订阅",
  "Password reset": "密码重置",
  "Internal dealer notification": "内部经销商通知",
  "Internal support notification": "内部客户支持通知",
  "Internal order notification": "内部订单通知",
};

export const adminPermissionLabels: Record<string, string> = {
  "system:staff:read": "Read staff",
  "system:staff:write": "Manage staff and roles",
  "system:audit:read": "Read audit logs",
  "catalog:product:read": "Read products",
  "catalog:product:write": "Manage products and variants",
  "catalog:price:write": "Manage price rules",
  "cms:page:write": "Manage CMS pages and home modules",
  "cms:media:write": "Manage media assets",
  "cms:contact:manage": "Manage contact leads",
  "b2b:dealer:review": "Review dealer applications",
  "b2b:dealer:read": "Read dealer data",
  "b2b:rfq:manage": "Manage RFQs and quotes",
  "order:read": "Read orders",
  "order:write": "Fulfill orders and refunds",
  "system:rbac:write": "Manage roles and permissions",
  "system:settings:write": "Manage system settings",
  "user:read": "Read customer accounts",
  "user:write": "Manage customer accounts and privacy",
  "reports:financial:read": "Read financial report amounts",
  "reports:read": "Read reports",
  "cms:read": "Read content",
  "cms:write": "Manage content",
  "media:read": "Read media",
  "media:write": "Manage media",
  "b2b:read": "Read dealer operations",
  "b2b:write": "Manage dealer operations",
  "contact:read": "Read customer support",
  "contact:write": "Manage customer support",
  "catalog:product:create": "Product create",
  "catalog:product:edit": "Product edit",
  "catalog:product:publish": "Product publish",
  "catalog:product:archive": "Product archive",
  "catalog:product:export": "Product export",
  "catalog:product:import": "Product import",
};
export const adminRoleLabels: Record<string, string> = {
  SUPER_ADMIN: "Super administrator",
  CATALOG_OPERATOR: "Catalog operations",
  CUSTOMER_SUPPORT: "Customer support",
  CONTENT_OPERATOR: "Content operations",
  DEALER_OPERATOR: "Dealer operations",
  ADMIN: "Administrator",
};
export const adminNotificationLabels: Record<string, string> = {
  "notification.default": "Business notification",
  "account.welcome": "Account welcome",
  "account.password-changed": "Password changed",
  "account.disabled": "Account disabled",
  "account.deletion.requested": "Account deletion requested",
  "account.privacy.resolved": "Privacy request resolved",
  "security.new_device": "New device sign-in",
  "dealer.application.confirmation": "Dealer application confirmation",
  "dealer.application.claim": "Claim dealer application",
  "dealer.application.resubmit": "Dealer application resubmitted",
  "dealer.application.review": "Dealer application review",
  "dealer.team.invitation": "Company team invitation",
  "dealer.team.disabled": "Company membership disabled",
  "dealer.rfq.submitted": "RFQ submitted",
  "dealer.rfq.quoted": "Quote ready",
  "dealer.rfq.expiring": "Quote expiring",
  "dealer.rfq.accepted": "Quote accepted",
  "dealer.rfq.rejected": "Quote rejected",
  "dealer.rfq.sales": "Sales RFQ notification",
  "dealer.order.confirmed": "Purchase order confirmed",
  "dealer.order.manual-create": "Assisted purchase order created",
  "dealer.order.processing": "Purchase order processing",
  "dealer.order.completed": "Purchase order completed",
  "dealer.order.adjusted": "Purchase order adjusted",
  "dealer.order.payment": "Purchase order payment updated",
  "dealer.order.shipment": "Purchase order shipped",
  "dealer.order.cancelled": "Purchase order cancelled",
  "dealer.order.return-requested": "Business return requested",
  "dealer.order.return-approved": "Business return approved",
  "dealer.order.return-rejected": "Business return rejected",
  "dealer.order.return-tracking": "Business return tracking updated",
  "dealer.order.return-withdrawn": "Business return withdrawn",
  "dealer.order.return-received": "Business return received",
  "dealer.order.refund-requested": "Business refund requested",
  "dealer.order.refund-reviewed": "Business refund reviewed",
  "dealer.order.refund-withdrawn": "Business refund withdrawn",
  "dealer.order.refund": "Business refund completed",
  "order.checkout": "Retail order created",
  "order.manual.create": "Assisted retail order created",
  "order.payment.update": "Retail payment updated",
  "order.shipment.create": "Retail shipment updated",
  "order.refund.create": "Retail refund processed",
  "order.return.update": "Retail return updated",
  "order.exchange.shipment": "Exchange shipped",
  "order.status.update": "Retail order status updated",
  "order.cancelled": "Retail order cancelled",
  "order.expired": "Retail order expired",
  "order.refund.update": "Retail refund updated",
  "contact.received": "Contact request received",
  "contact.reply": "Contact reply",
  "contact.status": "Contact request status updated",
  "newsletter.confirm": "Confirm newsletter subscription",
  "newsletter.unsubscribed": "Newsletter unsubscribed",
  "account.verify": "Email verification",
  "account.password-reset": "Password reset",
  "internal.dealer": "Internal dealer notification",
  "internal.support": "Internal support notification",
  "internal.orders": "Internal order notification",
};
