/** Customer account and dealer portal interface copy. Code values and user content are not translated. */
export const accountMessages: Record<string, string> = {
  "Discount ({currency})": "优惠（{currency}）",
  "Tax ({currency})": "税费（{currency}）",
  "Shipping ({currency})": "运费（{currency}）",
  "Amount ({currency})": "金额（{currency}）",
  "Current staff ({id})": "当前员工（{id}）",
  "Request history ({count})": "请求历史（{count}）",
  "Add selected variants ({count})": "添加已选款式（{count}）",
  confirmed: "已确认",
  processing: "处理中",
  shipped: "已发货",
  completed: "已完成",
  cancelled: "已取消",
  succeeded: "已成功",
  failed: "已失败",
  canceled: "已取消",
  "MOQ {min}; quantity multiple {multiple}; case size {caseSize}.":
    "最小起订量 {min}；订购倍数 {multiple}；每箱数量 {caseSize}。",
  "Only {count} units are currently available.":
    "当前仅有 {count} 件可用库存。",
  "SKU is duplicated in this upload.": "本次上传中存在重复 SKU。",
  "SKU does not exist or is not authorized.": "SKU 不存在或未获得采购授权。",
  "No authorized dealer price is available.": "暂无获授权的经销商价格。",
  "Inventory needs confirmation; please contact sales before ordering.":
    "库存需要确认，请在下单前联系销售人员。",
  "Requested quantity is unavailable; contact sales for lead time.":
    "无法满足所需数量，请联系销售确认交期。",
  "· Historical": " · 历史版本",
  "· Latest": " · 最新版本",
  "· Return": "· 退货",
  "· case gross weight": "· 整箱毛重",
  "· valid until": "· 有效期至",
  "(comma separated)": "（逗号分隔）",
  ") · expires": "）· 到期时间",
  "+ units; lower quantities have no current company price.":
    "件起；低于此数量暂无当前企业价格。",
  ", am authorized to use this company account, and accept these dealer portal terms.":
    "，确认有权使用本企业账户，并同意本经销商门户条款。",
  ", received": "，已收货",
  ", restocked": "，已重新入库",
  ". Agreement version: dealer-2026-09.": "。协议版本：dealer-2026-09。",
  ". Existing quote versions remain available for reference.":
    "。历史报价版本仍可查看。",
  ". Review these terms before using company prices, orders and private dealer resources.":
    "。使用企业价格、订单和经销商专属资源前，请阅读以下条款。",
  ". This validates authorization, tier pricing and live stock before an RFQ or PO is created.":
    "。创建询价单或采购订单前，将核验授权、阶梯价格和实时库存。",
  ": requested": "：申请数量",
  ADMIN: "管理员",
  APPROVED: "已批准",
  "APPROVED DEALER": "已认证经销商",
  "APPROVED DEALER CATALOG": "经销商授权目录",
  "Accept and continue": "同意并继续",
  "Accept invitation": "接受邀请",
  "Accept quote & create purchase order": "接受报价并创建采购订单",
  "Accepted on": "同意时间",
  "Accepting version": "接受报价版本",
  "Account created": "账户已创建",
  "Account security": "账户安全",
  "Account status": "账户状态",
  Active: "已启用",
  "Active sessions": "登录设备",
  "Add an address": "新增地址",
  "Add an authenticator to protect your customer and dealer access.":
    "绑定认证器，保护客户和经销商账户的访问安全。",
  "Add another address": "新增其他地址",
  "Add company address": "新增企业地址",
  "Add selected variants (": "添加已选款式（",
  "Add this key to your authenticator:": "请将此密钥添加到认证器：",
  "Add to cart": "加入购物车",
  "Added to cart. Open checkout to continue.": "已加入购物车，请前往结账。",
  "Address book": "地址簿",
  "Address label": "地址名称",
  "Adjust customer reference, terms or delivery details":
    "修改客户参考号、条款或配送信息",
  Adjustment: "调整",
  "Adjustment reason": "调整原因",
  "All rows are ready for the next business-document step.":
    "所有商品行均已通过验证，可以继续创建业务单据。",
  "Allowed payment methods": "允许的付款方式",
  "Amount (": "金额（",
  "An application with these details already exists.": "相同信息的申请已存在。",
  "Apartment / suite": "公寓／房间号",
  "Application ID": "申请编号",
  "Application progress": "申请进度",
  "Application received": "申请已收到",
  "Application submitted": "申请已提交",
  "Apply for verified dealer access. Our team will review the submitted business details before approval.":
    "申请认证经销商权限。我们的团队将在批准前审核您提交的企业信息。",
  "Apply here": "申请入驻",
  "Approve public changes": "批准公开信息变更",
  "Approve refund": "批准退款",
  "Approve return": "批准退货",
  Approved: "已批准",
  "Assign approved companies to price books. Rules attached to unassigned books never enter their dealer price calculation.":
    "为已认证企业分配价格表。未分配价格表的定价规则不会参与该企业的经销商价格计算。",
  "Assigned to": "负责人",
  "Assignment updated.": "负责人分配已更新。",
  Attachments: "附件",
  "Authenticator code": "认证器验证码",
  "Authenticator code (if enabled)": "认证器验证码（如已启用）",
  "Authorized catalog & prices": "授权商品及价格",
  "Authorized categories": "授权分类",
  "Authorized downloads": "授权下载",
  "Authorized products": "授权商品",
  "Authorized variants": "授权款式",
  "B2B administration": "企业采购管理",
  "B2B sales & fulfillment": "企业销售与履约",
  BILLING: "账单地址",
  BOTH: "收货及账单地址",
  BUYER: "采购员",
  Back: "上一步",
  "Back to purchase orders": "返回采购订单",
  "Bank receipt / settlement reference": "银行回执／结算参考号",
  "Bank transfer": "银行转账",
  "Become a WEMOVE Dealer": "成为 WEMOVE 经销商",
  "Billing address": "账单地址",
  "Book code": "价格表代码",
  "Book label": "价格表名称",
  "Browse products": "浏览商品",
  "Browser session": "浏览器会话",
  "Business contact:": "业务联系人：",
  "Business details": "企业信息",
  "Business email": "企业邮箱",
  "Business overview": "业务概况",
  "Business type": "企业类型",
  CLOSED: "已关闭",
  "CSV exceeds 100 KB": "CSV 文件不能超过 100 KB",
  Cancel: "取消",
  "Cancel order": "取消订单",
  "Cancel the unshipped order after the full remaining balance is refunded":
    "剩余款项全部退还后取消尚未发货的订单",
  Carrier: "承运商",
  "Case gross weight (g, optional)": "整箱毛重（克，选填）",
  "Change password": "修改密码",
  "Check the details below before submitting for administrator review.":
    "提交管理员审核前，请核对以下信息。",
  "Check the email provided in the application for your confirmation and secure claim link. Register and verify that email, then claim the application to receive review updates and submit corrections.":
    "请在申请填写的邮箱中查收确认邮件和安全认领链接。注册并验证该邮箱后，即可认领申请、查看审核进展和提交补充信息。",
  "Checking and uploading image…": "正在检查并上传图片…",
  Checkout: "结账",
  "Choose shipped items. Wait for approval before sending goods back.":
    "请选择已发货的商品。获得批准后再寄回商品。",
  "Choose the products and categories each company may purchase. Market and channel restrictions also apply. Hold Ctrl or Command to select multiple entries.":
    "选择各企业可采购的商品与分类，同时适用市场和渠道限制。按住 Ctrl 或 Command 可多选。",
  "Claim and view": "认领并查看",
  "Clear cart": "清空购物车",
  Company: "企业",
  "Company account": "企业账户",
  "Company account terms": "企业账户条款",
  "Company address book": "企业地址簿",
  "Company downloads": "企业下载中心",
  "Company name": "企业名称",
  "Company price": "企业专属价",
  "Company price books": "企业价格表",
  "Company product authorization & purchase rules": "企业商品授权与采购规则",
  "Company profile": "企业资料",
  "Company, team & addresses": "企业、团队与地址",
  "Company:": "企业：",
  "Completed bank transfer reference": "已完成银行转账的参考号",
  Confirm: "确认",
  "Confirm all units in this approved return have arrived. Record how many are sellable; the remainder will be recorded as received without restocking.":
    "确认该已批准退货中的全部商品均已收到。请记录可再次销售的数量；其余商品将记为已收货但不重新入库。",
  "Confirm authenticator": "确认认证器",
  "Confirm current password": "确认当前密码",
  "Confirm physical receipt": "确认实物收货",
  "Confirm purchase order": "确认采购订单",
  "Confirm receipt of": "确认收到",
  Contact: "联系方式",
  "Contact details": "联系信息",
  "Contact name": "联系人姓名",
  "Contact platform support": "联系平台客服",
  "Contact sales for lead time": "联系销售确认交期",
  "Contact sales to confirm inventory": "联系销售确认库存",
  "Contact support": "联系客服",
  "Contact the sales team for account and procurement assistance.":
    "如需账户或采购帮助，请联系销售团队。",
  Continue: "继续",
  "Continue to dealer portal": "前往经销商门户",
  "Continue to sign in": "前往登录",
  "Country (two-letter code)": "国家／地区（两位代码）",
  "Country / region": "国家／地区",
  "Country code (e.g. US)": "国家／地区代码（例如 US）",
  "Country or region": "国家／地区",
  "Create RFQ draft": "创建询价草稿",
  "Create a price book first.": "请先创建价格表。",
  "Create account": "创建账户",
  "Create book": "创建价格表",
  "Create company purchase order": "创建企业采购订单",
  "Create purchase order for company": "为企业创建采购订单",
  "Creating account…": "正在创建账户…",
  "Credit card": "信用卡",
  "Currency:": "币种：",
  "Current MFA code": "当前认证器验证码",
  "Current password": "当前密码",
  "Current prices and stock checked; reorder saved to procurement cart.":
    "已核验当前价格和库存，再次采购的商品已保存至采购车。",
  "Current staff (": "当前员工（",
  "Current status": "当前状态",
  "Customer PO number": "客户采购单号",
  "Customer PO:": "客户采购单号：",
  "Customer email": "客户邮件",
  "Customer login": "客户登录",
  DEALER: "经销商",
  "DEALER CENTER": "经销商中心",
  Dashboard: "工作台",
  "Data export downloaded.": "数据导出文件已下载。",
  "Dealer Application": "经销商申请",
  "Dealer Catalog | WEMOVE": "经销商目录 | WEMOVE",
  "Dealer Dashboard": "经销商工作台",
  "Dealer Portal": "经销商门户",
  "Dealer Sign in": "经销商登录",
  "Dealer dashboard": "经销商工作台",
  "Dealer login": "经销商登录",
  "Dealer portal terms": "经销商门户条款",
  "Dealer price": "经销商价格",
  "Dealer support": "经销商支持",
  "Dealer tools": "经销商工具",
  "Dealer workspace": "经销商工作区",
  "Decline and sign out": "拒绝并退出登录",
  "Default billing": "默认账单地址",
  "Default billing address": "默认账单地址",
  "Default dealer pricing": "默认经销商定价",
  "Default shipping": "默认收货地址",
  "Default shipping address ·": "默认收货地址 ·",
  Delete: "删除",
  "Deletion request received. Track the response below.":
    "注销申请已收到，可在下方查看处理进展。",
  "Deliver to:": "收货地址：",
  "Delivery details": "配送信息",
  "Delivery terms": "交货条款",
  "Directory changes awaiting platform review": "门店信息变更待平台审核",
  "Disable authenticator": "停用认证器",
  Discount: "优惠",
  "Discount (": "优惠（",
  "Display name": "显示名称",
  Distributor: "分销商",
  Download: "下载",
  "Download my data": "下载我的数据",
  "Download unavailable": "暂时无法下载",
  "Download your profile, addresses, orders, preferences and requests. Deletion requests are reviewed by support; open orders and company memberships must be closed or transferred. Commercial records required for fulfillment and accounting may be retained.":
    "下载您的资料、地址、订单、偏好设置和申请记录。注销申请将由客服审核，未完成订单和企业成员关系须先关闭或转移。履约和记账所必需的交易记录可能被保留。",
  EXACT: "显示准确数量",
  EXPIRED: "已过期",
  "Each image must be 5 MB or smaller.": "每张图片不能超过 5 MB。",
  Edit: "编辑",
  "Edit address": "编辑地址",
  Email: "邮箱",
  "Email claim token (first claim only)": "邮件认领码（仅首次认领需要）",
  "Email me offers and news (optional)": "通过邮件接收优惠和资讯（选填）",
  "Email me product updates (optional)": "通过邮件接收商品更新（选填）",
  "Email offers and news": "邮件优惠与资讯",
  "Email:": "邮箱：",
  "Enable an independent public store page": "启用独立的公开门店页面",
  "Enabled. A code is required at every login.":
    "已启用。每次登录均需输入验证码。",
  "Enter a review reason of at least five characters.":
    "请输入至少 5 个字符的审核原因。",
  "Enter address below": "在下方填写地址",
  "Enter the current 6-digit MFA code.": "请输入当前的 6 位认证器验证码。",
  "Enter the current six-digit MFA code.": "请输入当前的 6 位认证器验证码。",
  "Enter your current 6-digit MFA code before saving.":
    "保存前请输入当前的 6 位认证器验证码。",
  "Enter your current six-digit MFA code.": "请输入当前的 6 位认证器验证码。",
  "Estimated dealer prices; a sales quote is required before purchase.":
    "此处为经销商预估价格；采购前需取得销售报价。",
  "For approved wholesale partners only.": "仅限已通过审核的批发合作伙伴。",
  "For personal shopping and order tracking.": "用于个人购物和订单查询。",
  "Forgot password?": "忘记密码？",
  "Full name": "姓名",
  HEADQUARTERS: "总部地址",
  HIDDEN: "隐藏库存",
  "I agree to the": "我同意",
  "I confirm I am 18 or older.": "我确认已年满 18 周岁。",
  "I confirm that the information is accurate and that I am authorized to apply for this business. I agree to the":
    "我确认所填信息准确，且有权代表本企业申请。我同意",
  "I have read version": "我已阅读版本",
  "IP unavailable": "暂无 IP 信息",
  "If this unclaimed application belongs to your verified email, a claim link will be sent. Allow one minute between requests.":
    "如果这份未认领申请属于您已验证的邮箱，系统将发送认领链接。两次请求之间请间隔一分钟。",
  "If your company requires an authenticator, enable it here and sign in again before purchasing or accessing private dealer resources.":
    "如果企业要求使用认证器，请在此启用并重新登录，然后再采购或访问经销商专属资源。",
  "In stock": "有货",
  "Includes tax": "含税费",
  "Inspection note": "验收备注",
  "Internal note": "内部备注",
  "Internal note (uncheck to email customer)":
    "内部备注（取消勾选则发送邮件给客户）",
  "Inventory display": "库存显示方式",
  "Inventory:": "库存：",
  "Invitation accepted. Sign in at Dealer login to activate the company session.":
    "邀请已接受。请通过经销商入口登录以启用企业会话。",
  "Invitation token": "邀请令牌",
  "Invite email": "受邀人邮箱",
  "Issue a revised quote": "发布修订报价",
  "Issue quote version": "发布报价版本",
  "Item details and private photos": "商品问题说明及私密照片",
  KB: "KB",
  "KB ·": "KB ·",
  Language: "语言",
  "Last active": "最近活跃时间",
  "Last review:": "上次审核：",
  "Latest 100 requests. Amounts use the quoted settlement currency.":
    "显示最近 100 条申请，金额按报价的结算币种显示。",
  "Latest company resources": "最新企业资源",
  "Load saved procurement cart": "载入已保存的采购车",
  "Loading after-sales records…": "正在加载售后记录…",
  "Loading company dashboard…": "正在加载企业工作台…",
  "Loading company documents…": "正在加载企业单据…",
  "Loading the current terms…": "正在加载当前条款…",
  "Loading your account…": "正在加载账户…",
  "Local test payment. No card is charged.":
    "本地测试支付，不会从银行卡实际扣款。",
  MOQ: "最小起订量",
  "MSRP USD": "建议零售价（美元）",
  "Manage company profile, team and addresses": "管理企业资料、团队与地址",
  "Message saved.": "消息已保存。",
  "My Account": "我的账户",
  Name: "姓名",
  "New here?": "还没有账户？",
  "New password": "新密码",
  "New request": "新建申请",
  "No RFQs yet. Start from Quick Order to validate your items.":
    "暂无询价单。请先前往快速下单核验商品。",
  "No authorized downloads are published yet.": "暂无已发布的授权下载资源。",
  "No authorized products are available.": "暂无可采购的授权商品。",
  "No authorized resources published yet.": "暂无已发布的授权资源。",
  "No current announcements.": "暂无公告。",
  "No orders yet.": "暂无订单。",
  "No pending quotations.": "暂无待处理报价。",
  "No purchase orders yet. Accept a valid quote to create one.":
    "暂无采购订单。接受有效报价后即可创建。",
  "No refund requests.": "暂无退款申请。",
  "No return linked": "未关联退货",
  "No return requests.": "暂无退货申请。",
  "Not a dealer yet?": "还不是经销商？",
  "Not provided": "未提供",
  "Online sales": "线上销售",
  "Open a support request": "提交客服请求",
  "Open attachment": "打开附件",
  "Opening hours and business information": "营业时间及经营信息",
  "Optional. PDF, JPG or PNG; maximum 5 MB. Stored privately.":
    "选填。支持 PDF、JPG 或 PNG，最大 5 MB，文件将私密存储。",
  "Optional: describe each selected item and attach up to five JPG, PNG or WebP photos, 5 MB each. Photos are available to you and authorized support staff.":
    "选填：描述每件所选商品的问题，最多上传 5 张 JPG、PNG 或 WebP 照片，每张不超过 5 MB。照片仅您和获授权的客服人员可查看。",
  "Order cancelled and reserved inventory returned.":
    "订单已取消，预留库存已释放。",
  Orders: "订单",
  "Orders awaiting confirmation": "待确认订单",
  "Orders awaiting payment": "待付款订单",
  Other: "其他",
  "Other device": "其他设备",
  "Other sessions revoked.": "其他设备已退出登录。",
  "Owners and buyers can save these items as a draft, then submit it for quotation.":
    "企业所有者和采购员可将这些商品保存为草稿，然后提交询价。",
  PDF: "PDF",
  PENDING_REVIEW: "待审核",
  Paid: "已付款",
  Password: "密码",
  "Password (8+ chars, letters & numbers)": "密码（至少 8 位，含字母和数字）",
  "Paste up to 100 rows as": "最多粘贴 100 行，格式为",
  "Pause new orders": "暂停新订单",
  "Pay by credit card": "信用卡支付",
  "Payment method": "付款方式",
  "Payment terms": "付款条款",
  "Pending refunds reserve the refund balance. Received returns restore only the units confirmed as sellable; damaged goods remain outside available inventory.":
    "待处理退款会占用可退款余额。退货收货时，仅确认可再次销售的商品会恢复为可用库存，损坏商品不会计入可用库存。",
  "Pending:": "待处理：",
  Phone: "电话",
  "Photo for": "商品照片：",
  "Physical store": "实体门店",
  "Placing order…": "正在下单…",
  "Planned quantity": "计划采购数量",
  "Platform announcements": "平台公告",
  "Please complete all contact fields.": "请完整填写联系信息。",
  "Please confirm that the information is accurate and authorized.":
    "请确认信息准确且您已获得申请授权。",
  "Please provide the company name, registration number, country and business type.":
    "请填写企业名称、注册号、国家／地区和企业类型。",
  "Postal code": "邮政编码",
  "Prepare quote": "准备报价",
  "Price book": "价格表",
  "Price level:": "价格等级：",
  "Price shown for": "价格适用数量",
  "Price valid until": "价格有效期至",
  "Prices are in": "价格币种为",
  "Prices are resolved for your company and update with order quantity.":
    "价格依据企业授权计算，并随采购数量更新。",
  Priority: "优先级",
  "Privacy Policy": "隐私政策",
  "Privacy policy": "隐私政策",
  "Procurement cart saved.": "采购车已保存。",
  "Product / SKU": "商品／SKU",
  "Product unavailable": "商品不可用",
  "Product updates": "商品更新",
  "Product variant": "商品款式",
  "Profile and subscriptions": "个人资料与订阅",
  "Provider/transfer reference:": "支付机构／转账参考号：",
  "Public business phone": "公开业务电话",
  "Public dealer directory": "公开经销商目录",
  "Public details require platform review before publishing. Authorized categories come from the company catalog policy. Turning off publication hides the current listing immediately.":
    "公开信息须经平台审核后发布。授权分类来自企业目录策略。关闭发布将立即隐藏当前门店信息。",
  "Public logo URL": "公开标志图片地址",
  "Publish store in dealer directory": "在经销商目录中公开门店",
  "Purchase order": "采购订单",
  "Purchase orders": "采购订单",
  Qty: "数量",
  Qualification: "资质",
  "Qualification document": "资质文件",
  "Qualification files must be PDF, JPG or PNG and no larger than 5 MB.":
    "资质文件须为 PDF、JPG 或 PNG，且不超过 5 MB。",
  "Qualification proof is optional for initial submission and can be provided as a secure link.":
    "首次提交时资质证明为选填，可通过安全链接提供。",
  "Quick Order": "快速下单",
  "Quick Order | WEMOVE Dealer": "快速下单 | WEMOVE 经销商",
  "Quick order & procurement cart": "快速下单与采购车",
  "Quotations to review": "待审核报价",
  "Quotes & Purchase Orders | WEMOVE": "报价与采购订单 | WEMOVE",
  "Quotes & purchase orders": "报价与采购订单",
  "Quotes awaiting a decision": "待确认报价",
  "RFQ attachment": "询价附件",
  Reason: "原因",
  "Reason for cancelling this purchase order:": "取消该采购订单的原因：",
  "Reason for declining this quote:": "拒绝该报价的原因：",
  "Reason for deleting your account": "账户注销原因",
  "Received return (when applicable)": "已收到的退货（如适用）",
  "Recent orders": "最近订单",
  "Record partial shipment": "记录分批发货",
  "Record receipt & restock sellable units": "确认收货并入库可售商品",
  "Record shipment": "记录发货",
  "Reference number": "参考编号",
  Refresh: "刷新",
  "Refund confirmation pending · attempts": "退款待确认 · 已尝试次数",
  "Refund history": "退款记录",
  "Refund withdrawal reason": "撤销退款原因",
  "Registered customer downloads": "注册客户下载中心",
  "Registration failed.": "注册失败。",
  "Registration number": "注册号",
  "Reject changes": "拒绝变更",
  "Reject quote": "拒绝报价",
  "Reject refund": "拒绝退款",
  "Reject return": "拒绝退货",
  Rejected: "已拒绝",
  "Rejection reason:": "拒绝原因：",
  Remove: "移除",
  "Remove address": "删除地址",
  "Reorder with current prices": "按当前价格再次采购",
  "Reply or internal note": "回复或内部备注",
  "Request a refund": "申请退款",
  "Request a return": "申请退货",
  "Request a sales quote": "申请销售报价",
  "Request account deletion": "申请注销账户",
  "Request failed": "请求失败",
  "Request failed. Please try again.": "请求失败，请重试。",
  "Request history (": "请求历史（",
  "Request notes": "询价备注",
  "Request title": "询价标题",
  "Requests for quotation": "询价单",
  "Require MFA for dealer accounts": "要求经销商账户启用双因素认证",
  "Require customer PO number": "要求填写客户采购单号",
  "Required for every staff login. Resetting signs you out and requires enrolling an authenticator at the next login.":
    "员工每次登录均须验证。重置后会退出登录，下次登录时须重新绑定认证器。",
  "Resend claim email": "重新发送认领邮件",
  "Reserve inventory": "库存预留时机",
  "Reset authenticator": "重置认证器",
  "Resolve the row errors before continuing.":
    "请先修正各商品行的错误，再继续操作。",
  "Resolving prices…": "正在计算价格…",
  "Restrict catalog to selected products/categories (no selections denies all)":
    "仅允许采购所选商品／分类（未选择则全部禁止）",
  Result: "结果",
  Retailer: "零售商",
  "Retry payment provider": "重新请求支付机构",
  "Return carrier": "退货承运商",
  "Return history": "退货记录",
  "Return to home": "返回首页",
  "Returns & refunds": "退货与退款",
  "Returns, refunds & after-sales history": "退货、退款与售后记录",
  "Review application": "核对申请",
  "Review company orders, quotations and purchasing resources.":
    "查看企业订单、报价与采购资源。",
  "Review is pending.": "等待审核。",
  "Review message:": "审核消息：",
  "Review procurement cart": "查看采购车",
  "Review reason": "审核原因",
  "Review submitted public content": "查看提交的公开信息",
  "Review:": "审核结果：",
  Role: "角色",
  "Role:": "角色：",
  Row: "行号",
  SHIPPING: "收货地址",
  SKU: "SKU",
  "SKU and quantity rows": "SKU 与数量",
  "SKU, quantity": "SKU、数量",
  "SMS offers and news": "短信优惠与资讯",
  STATUS: "仅显示库存状态",
  SUSPENDED: "已暂停",
  "Sales region:": "销售区域：",
  "Same as shipping": "与收货地址相同",
  "Save address": "保存地址",
  "Save address changes": "保存地址变更",
  "Save adjustment with audit record": "保存调整并记录审计日志",
  "Save assignment": "保存分配",
  "Save company access": "保存企业权限",
  "Save company policy": "保存企业策略",
  "Save message": "保存消息",
  "Save procurement cart": "保存采购车",
  "Save products using the wishlist button on a product page.":
    "可在商品详情页点击心愿单按钮收藏商品。",
  "Save profile": "保存资料",
  "Save return shipment": "保存退货物流",
  "Saved shipping address": "已保存的收货地址",
  "Saved successfully.": "保存成功。",
  "Saved. Current status and history are shown below.":
    "已保存，可在下方查看当前状态与历史记录。",
  "Search files": "搜索文件",
  "Security and devices": "安全与设备",
  "Select a type": "选择类型",
  "Selected variants were added to your procurement cart.":
    "所选款式已加入采购车。",
  "Send invitation": "发送邀请",
  "September store replenishment": "九月门店补货",
  "Set up authenticator": "绑定认证器",
  "Settlement currency": "结算币种",
  "Shipment:": "发货记录：",
  "Shipped goods require a received return. Approved bank/PO refunds need a recorded transfer; card refunds wait for the payment provider’s confirmation.":
    "已发货商品须先完成退货收货。已批准的银行转账／采购订单退款需记录转账信息；银行卡退款须等待支付机构确认。",
  "Shipping (": "运费（",
  "Shopping cart": "购物车",
  "Sign in": "登录",
  "Sign in failed.": "登录失败。",
  "Sign in to manage your account and shopping cart.":
    "登录以管理您的账户和购物车。",
  "Sign in with the verified customer email used on the application.":
    "请使用申请中已验证的客户邮箱登录。",
  "Sign out": "退出登录",
  "Sign out other devices": "退出其他设备",
  "Signing in…": "正在登录…",
  Simulate: "模拟",
  "Some application details are invalid. Please review and try again.":
    "部分申请信息无效，请检查后重试。",
  "Staff authorization / reason": "员工授权／原因",
  "Staff list unavailable. Current assignment is retained; reload before assigning another person.":
    "员工列表暂不可用。当前负责人已保留，分配其他人员前请重新加载。",
  "State / province": "省／州",
  "State / region": "省／州／地区",
  "Status:": "状态：",
  "Store description": "门店介绍",
  "Street address": "街道地址",
  "Submit application": "提交申请",
  "Submit for quotation": "提交询价",
  "Submit refund request": "提交退款申请",
  "Submit return request": "提交退货申请",
  "Submitting…": "正在提交…",
  "Support:": "客服：",
  "Tags (comma separated)": "标签（逗号分隔）",
  "Target delivery date": "期望交货日期",
  "Target delivery:": "期望交货日期：",
  Tax: "税费",
  "Tax (": "税费（",
  Team: "团队",
  "Tell us who should receive application updates.":
    "请填写接收申请进展通知的联系人。",
  Terms: "条款",
  "Thank you for applying": "感谢您的申请",
  "The application could not be submitted. Please try again.":
    "申请提交失败，请重试。",
  "The order will be cancelled only after the refund is confirmed.":
    "退款确认后才会取消订单。",
  "This device": "当前设备",
  "This records a staff-created order with your identity and reason. Company acceptance and account consent records are not changed.":
    "此操作将记录由员工代建的订单，以及您的身份和原因，不会修改企业接受报价及账户同意记录。",
  "Tier price": "等级价格",
  "Too many attempts. Please wait a moment before trying again.":
    "尝试次数过多，请稍后重试。",
  Total: "合计",
  "Track or claim an application": "查询或认领申请",
  "Track or claim this application": "查询或认领此申请",
  "Track requests, compare quote versions and follow company purchases.":
    "跟踪询价申请、比较报价版本并查看企业采购进展。",
  "Track your dealer application": "查询经销商申请",
  "Tracking number": "物流单号",
  "Two-factor authentication": "双因素认证",
  USD: "美元",
  "Unable to cancel order.": "无法取消订单。",
  "Unable to clear cart.": "无法清空购物车。",
  "Unable to create request.": "无法创建询价单。",
  "Unable to load dealer catalog.": "无法加载经销商目录。",
  "Unable to load dealer terms.": "无法加载经销商条款。",
  "Unable to load your account.": "无法加载您的账户。",
  "Unable to remove image": "无法删除图片",
  "Unable to remove item.": "无法移除商品。",
  "Unable to save acceptance.": "无法保存条款同意记录。",
  "Unable to save assignment.": "无法保存分配。",
  "Unable to save message.": "无法保存消息。",
  "Unable to save.": "无法保存。",
  "Unable to update cart.": "无法更新购物车。",
  "Unable to upload image.": "无法上传图片。",
  "Unable to validate this order.": "无法验证此订单。",
  Unassigned: "未分配",
  Unavailable: "不可用",
  "Unit price": "单价",
  "Update member": "更新成员",
  "Update your dealer application": "更新经销商申请",
  "Upload SKU CSV": "上传 SKU CSV 文件",
  Use: "用途",
  "Use 8–72 characters with at least one letter and one number.":
    "请输入 8–72 位字符，至少包含一个字母和一个数字。",
  "Use a verified customer account with the invited email.":
    "请使用受邀邮箱对应且已验证的客户账户。",
  "Use as default": "设为默认",
  "Use at least eight characters with letters and numbers. Changing your password signs out every device.":
    "请输入至少 8 位字符，包含字母和数字。修改密码后，所有设备将退出登录。",
  VIEWER: "只读成员",
  "Valid total:": "有效商品合计：",
  "Valid until (your local time)": "有效期至（本地时间）",
  "Validate order": "验证订单",
  "Validating…": "正在验证…",
  Variant: "款式",
  Version: "版本",
  "View application": "查看申请",
  "View purchase order": "查看采购订单",
  WEMOVE: "WEMOVE",
  "WEMOVE Business": "WEMOVE 企业采购",
  "WEMOVE toys are for kids — accounts are for adults only.":
    "WEMOVE 玩具面向儿童，账户仅供成年人注册使用。",
  "Website terms": "网站条款",
  "Welcome back": "欢迎回来",
  "When staff confirms the order": "员工确认订单时",
  "When the dealer submits the order": "经销商提交订单时",
  Wholesaler: "批发商",
  Wishlist: "心愿单",
  "Withdraw refund request": "撤销退款申请",
  "Withdraw return": "撤销退货",
  "Withdrawal reason": "撤销原因",
  "Your account is active and ready to use.": "您的账户已激活，可以开始使用。",
  "Your cart is empty.": "购物车为空。",
  "Your data": "您的数据",
  "Your dealer application has entered administrator review. Please keep the reference number below for support enquiries.":
    "您的经销商申请已进入管理员审核，请保存下方参考编号以便查询。",
  "Your draft is saved on this device and, when signed in, to your account.":
    "草稿已保存在当前设备，登录后也会同步至您的账户。",
  "Your wholesale prices": "您的批发价格",
  address: "地址",
  and: "及",
  "and dealer application declaration (version dealer-2026-09).":
    "及经销商申请声明（版本 dealer-2026-09）。",
  "and shipping": "及运费",
  "attachment(s) uploaded.": "个附件已上传。",
  "creates one purchase order and reserves stock. Total:":
    "将创建一个采购订单并预留库存。合计：",
  days: "天",
  each: "每件",
  "privacy policy": "隐私政策",
  "product lines": "条商品",
  quantity: "数量",
  "reservation recorded": "已预留库存",
  "reservation released": "已释放预留库存",
  "reserved after staff confirmation": "员工确认后预留库存",
  "returnable)": "件可退）",
  transferred: "已转账",
  "· Available to request": "· 可申请金额",
  "· Expires": "· 到期时间",
  "· Payment": "· 付款",
  "· Quote v": "· 报价版本",
  "· Refunded": "· 已退款",
  "· Shipping": "· 运费",
  "· case": "· 每箱数量",
  "· lead time": "· 交期",
  "· multiple": "· 订购倍数",
  "· retry after": "· 下次重试时间",
  "· sellable units out of": "· 可售数量／总数",
  "· unit price": "· 单价",
  "· up to": "· 最多",
  "· v": "· 版本",
  "— uploaded privately": "— 已私密上传",
  "— what happened?": "— 问题描述",
  "Quantity for {v0}": "{v0} 的数量",
  "Check {v0} for the verification email before signing in.":
    "登录前请查收 {v0} 的验证邮件并完成验证。",
  "Select {v0}": "选择 {v0}",
  g: "克",
  "· {v0} g each": "· 每件 {v0} 克",
  "· Retail sale USD {v0}": "· 零售价格 {v0} 美元",
  "{v0} units available": "可用库存 {v0} 件",
  "{v0} · {v1} {v2} each · {v3} · lead time {v4} days":
    "{v0} · 每件 {v1} {v2} · {v3} · 交期 {v4} 天",
  "· Cancellation reason: {v0}": "· 取消原因：{v0}",
  "Change purchase order to {v0}?": "是否将采购订单改为“{v0}”？",
  "Mark {v0}": "标记为{v0}",
  Quantity: "数量",
  Recipient: "收件人",
  City: "城市",
  "Saved.": "已保存。",
  Business: "企业",
  Review: "审核",
  OWNER: "企业管理员",
  MORE_INFO_REQUIRED: "待补充信息",
  QUOTED: "已报价",
  ACCEPTED: "已接受",
  FULFILLED: "已履约",
  PARTIALLY_SHIPPED: "部分发货",
  PARTIALLY_REFUNDED: "部分退款",
  REFUNDED: "已退款",
  WITHDRAWN: "已撤销",
  RECEIVED: "已收货",
  REQUESTED: "已申请",
  AWAITING_TRANSFER: "等待转账",
  PENDING_CONFIRMATION: "待确认",
  RETRY_PENDING: "待重试",
  IN_STOCK: "有货",
  LEAD_TIME: "按交期供货",
  CHECK_AVAILABILITY: "请确认库存",
  PRIVATE: "私密",
  PUBLIC: "公开",
  REGISTERED: "注册用户",
  LOW: "低",
  NORMAL: "普通",
  HIGH: "高",
  URGENT: "紧急",
  CARD: "信用卡",
  BANK_TRANSFER: "银行转账",
  PO: "采购订单账期",
  SUCCEEDED: "已成功",
  "Shipping address": "收货地址",
  displayName: "显示名称",
  taxId: "税务登记号",
  businessType: "企业类型",
  salesRegion: "销售区域",
  salesRepresentative: "销售代表",
  phone: "电话",
  website: "网站",
  city: "城市",
  publicAddress: "公开门店地址",
  salesContact: "销售联系方式",
  latitude: "纬度",
  longitude: "经度",
  recipient: "收件人",
  country: "国家／地区",
  addressLine: "详细地址",
  postalCode: "邮政编码",
  publicListing: "公开门店",
  publicDetail: "独立公开门店页面",
  publicPhone: "公开业务电话",
  publicLogo: "公开标志图片",
  publicRegion: "省／州",
  publicPostalCode: "邮政编码",
  publicHours: "营业时间",
  publicDescription: "门店介绍",
  onlineStore: "线上销售",
  physicalStore: "实体门店",
  submittedAt: "提交时间",
  markets: "销售市场",
  channels: "渠道",
  moq: "最小起订量",
  multiple: "订购倍数",
  caseSize: "每箱数量",
  leadTimeDays: "交期（天）",
  status: "状态",
  priority: "优先级",
  assignedTo: "负责人",
  assignedTeam: "负责团队",
  tags: "标签",
  create: "创建",
  created: "已创建",
  update: "更新",
  updated: "已更新",
  assign: "分配",
  assigned: "已分配",
  reply: "回复",
  note: "内部备注",
  confirmation: "订单确认书",
  quote: "报价单",
  invoice: "发票",
  "packing-list": "装箱单",
  CATALOG: "产品目录",
  MANUAL: "操作手册",
  CERTIFICATE: "认证文件",
  IMAGE: "图片",
  VIDEO: "视频",
  DOCUMENT: "文档",
  OTHER: "其他",
  "WEMOVE Dealer Portal Terms": "WEMOVE 经销商门户条款",
  "Your company account": "您的企业账户",
  "Use the portal only for the approved company shown below and within the permissions assigned to you. Keep company, contact and delivery information accurate. Each person must use their own verified account; protect passwords and authenticator codes and report suspected unauthorized access.":
    "请仅代表下方显示的已认证企业，并在分配给您的权限范围内使用本门户。请保持企业、联系及配送信息准确。每位使用者须使用本人已验证的账户，妥善保护密码和认证器验证码，并报告疑似未经授权的访问。",
  "Authorized catalog and confidential information": "授权目录与保密信息",
  "Dealer prices, quotations, inventory information and private downloads are provided for your company’s procurement and authorized sales activity. Do not share another company’s information, disclose private prices or redistribute restricted files outside the approved business purpose.":
    "经销商价格、报价、库存信息及私密下载资源仅供本企业采购及获授权的销售活动使用。不得分享其他企业的信息、泄露非公开价格，或超出获批准的业务用途传播受限文件。",
  "Quotes and purchase orders": "报价与采购订单",
  "Check the market, currency, quantities, minimum order requirements, delivery addresses and payment terms before submitting. A submitted purchase order is subject to the confirmation shown in the portal. The accepted quotation and order records identify agreed prices and terms; changes require a recorded request or confirmation.":
    "提交前请核对市场、币种、数量、最小起订要求、配送地址及付款条款。已提交的采购订单以门户显示的确认结果为准。已接受的报价及订单记录载明双方确认的价格和条款；变更须通过有记录的申请或确认。",
  "Payments, delivery and after-sales requests": "付款、配送与售后申请",
  "Use the payment instructions and deadlines on the confirmed order. Delivery estimates and stock availability may change before confirmation. Report discrepancies and request cancellations, returns or refunds through the order or company support channel, including the relevant quantities and evidence. Approved outcomes are recorded against the order.":
    "请按已确认订单上的付款指引及期限付款。订单确认前，预计交期和库存情况可能变化。如发现差异，或需取消订单、退货或退款，请通过订单或企业支持渠道提出，并附上相关数量及证据。已批准的处理结果将记录在订单中。",
  "Personal data and records": "个人数据与记录",
  "Company contacts, addresses, consent records and procurement records are used to provide account access, order processing and support as described in the privacy policy. Transactional account and order messages continue when marketing emails are disabled. Account closure or deletion requests are reviewed alongside outstanding orders and required record retention.":
    "按照隐私政策，企业联系人、地址、同意记录和采购记录用于提供账户访问、订单处理及支持服务。关闭营销邮件后，仍会发送与账户及订单交易相关的通知。账户关闭或注销申请将结合未完成订单及必要的记录保存要求进行审核。",
  "Authority and updates": "授权与条款更新",
  "Email language": "邮件语言",
  channel: "当前渠道",
  ACCOUNT: "企业账期",
  RETAILER: "零售商",
  DISTRIBUTOR: "分销商",
  WHOLESALER: "批发商",
  "By accepting, you confirm that you are authorized to access this company’s dealer account and that you have read this version of the portal terms. Your company, user account, version, acceptance time and request IP are recorded. A new version requires another explicit acceptance before dealer services resume.":
    "点击同意即表示您确认有权访问本企业的经销商账户，并已阅读本版本的门户条款。系统会记录您的企业、用户账户、条款版本、同意时间和请求 IP。条款发布新版本后，须再次明确同意才能恢复经销商服务。",
};
