/** Chinese text for the public website and retail order journeys. */
export const publicMessages: Record<string, string> = {
  "Your cart & checkout": "购物车与结算",
  "Guest items awaiting merge": "待合并的游客购物车商品",
  "Reduce unavailable quantities or remove an item, then retry. Your signed-in cart is shown below.":
    "请减少缺货商品的数量或移除商品后重试。下方显示的是当前账号的购物车。",
  Quantity: "数量",
  Remove: "移除",
  "Retry merge": "重新合并",
  "Your cart is empty.": "购物车暂无商品。",
  "Browse products": "浏览商品",
  "Your cart is saved on this device.": "购物车已保存在此设备上。",
  "Sign in to merge it and check out": "登录以合并购物车并结算",
  Market: "销售市场",
  "Online retail is closed in this market.": "此市场暂未开放在线零售。",
  "Where to Buy": "购买渠道",
  "Contact us": "联系我们",
  "Shipping address": "收货地址",
  "Use saved address": "使用已保存的地址",
  "Enter address": "填写地址",
  "Billing address is the same": "账单地址与收货地址相同",
  Delivery: "配送方式",
  Standard: "标准配送",
  Express: "加急配送",
  "Discount code": "优惠码",
  "Order review": "订单确认",
  "Prices changed since items were added. These are the current prices.":
    "部分商品价格在加入购物车后发生变化。此处显示当前价格。",
  "Place order & continue to payment": "提交订单并付款",
  "Enter your address and review current prices, tax and delivery charges before placing the order.":
    "请填写地址，并在提交订单前确认当前价格、税费和运费。",
  "Choose up to four products. Highlighted rows show differences.":
    "最多选择四款商品进行比较，高亮行表示存在差异。",
  "WEMOVE product comparison": "WEMOVE 商品比较",
  Product: "商品",
  "Select product": "选择商品",
  Compare: "比较",
  "Product comparison with differences highlighted":
    "商品比较，差异项已高亮显示",
  Feature: "属性",
  Different: "存在差异",
  "Select products above to compare.": "请在上方选择要比较的商品。",
  "Some selected products are no longer published in this market.":
    "部分选中的商品已在此市场下架。",
  "Your name": "姓名",
  Email: "电子邮箱",
  "Country (optional)": "国家或地区（选填）",
  "Request type": "咨询类型",
  Subject: "主题",
  Message: "留言内容",
  "Attachments (optional, up to five JPG/PNG/WebP/PDF files, 5 MB each)":
    "附件（选填，最多五个 JPG、PNG、WebP 或 PDF 文件，每个不超过 5 MB）",
  "I agree to the": "我同意",
  "Privacy Policy": "隐私政策",
  "and consent to processing this request. Do not include payment credentials or information about children.":
    "，并同意为处理本次请求使用相关信息。请勿填写支付凭据或儿童个人信息。",
  Website: "网站",
  "Contact Us": "联系我们",
  "We reply within 2 business days.": "我们将在两个工作日内回复。",
  "Content temporarily unavailable": "内容暂时无法加载",
  "Please try again shortly.": "请稍后重试。",
  "Cookie settings": "Cookie 设置",
  "Essential cookies support authentication, security and shopping. Optional analytics are stored only after your consent; they exclude names, contact details and payment credentials. Pseudonymous session, product and order references help us measure completed journeys.":
    "必要 Cookie 用于身份验证、安全防护和购物功能。可选分析数据仅在您同意后保存，不包含姓名、联系方式或支付凭据；匿名化的会话、商品及订单标识用于分析服务使用情况。",
  "Allow optional analytics": "允许可选的数据分析",
  "Save preferences": "保存偏好设置",
  "Your preferences have been saved.": "偏好设置已保存。",
  "Find a dealer": "查找经销商",
  "Dealer directory temporarily unavailable. Please try again.":
    "经销商目录暂时无法加载，请稍后重试。",
  "All dealers": "所有经销商",
  "If an eligible account exists, reset instructions are on the way.":
    "如果该邮箱对应可用账号，重置说明将发送至邮箱。",
  "Reset your password": "重置密码",
  "Enter your email and we will send instructions if an eligible account exists.":
    "请输入邮箱。如果存在符合条件的账号，我们会发送密码重置说明。",
  "Email subscription": "邮件订阅",
  "Confirm your subscription to receive play ideas and product news.":
    "确认订阅，接收玩法灵感与商品资讯。",
  "Confirm subscription": "确认订阅",
  Unsubscribe: "取消订阅",
  "Active play, made thoughtful": "用心设计，尽情玩乐",
  "Play starts with moving.": "从运动开始玩乐",
  "Thoughtful sports toys for confident movement at home, at school and outside.":
    "为家庭、学校与户外活动提供运动玩具，让孩子自信运动。",
  "Shop products": "选购商品",
  "Become a dealer": "申请成为经销商",
  "A collection of active play toys on an outdoor sports court":
    "户外运动场上的运动玩具组合",
  "WEMOVE product principles": "WEMOVE 商品理念",
  "Find their kind of play": "发现适合的玩法",
  "Start with a movement, then discover the toys that make it feel natural.":
    "从一个动作开始，发现让运动自然融入生活的玩具。",
  "View every product": "查看全部商品",
  "Ready for the next game": "准备迎接下一场游戏",
  "Bring better play to your shelves.": "为您的货架带来更多玩乐选择。",
  "Dealer access, product resources and ordering tools in one practical place.":
    "在同一平台获取经销商服务、商品资料与订购工具。",
  "Apply for dealer access": "申请经销商权限",
  "Play & Learn": "玩乐与学习",
  "Activity guides, skills and ideas for active family play.":
    "探索亲子运动的活动指南、技巧与灵感。",
  "Search guides": "搜索玩法指南",
  Category: "分类",
  "All categories": "所有分类",
  "Find guides": "查找指南",
  "No published guides match your search.": "暂无符合搜索条件的已发布指南。",
  "Guide pages": "指南分页",
  Previous: "上一页",
  Next: "下一页",
  "Choose a new password": "设置新密码",
  "Password updated.": "密码已更新。",
  "Sign in": "登录",
  "New password": "新密码",
  "Use 8–72 characters, including a letter and a number.":
    "请输入 8 至 72 个字符，至少包含一个字母和一个数字。",
  "Confirm new password": "确认新密码",
  "Result type": "结果类型",
  results: "条结果",
  "Try a broader phrase or browse these products":
    "请尝试更宽泛的关键词，或浏览以下商品",
  "Did you mean:": "您是否想搜索：",
  "Clear type filters": "清除类型筛选",
  "Clear search": "清除搜索",
  "Contact support": "联系客服",
  "Search pages": "搜索结果分页",
  "Search temporarily unavailable. Please try again.":
    "搜索暂时不可用，请稍后重试。",
  Downloads: "资料下载",
  "Published instructions, certificates and resources.":
    "已发布的说明书、证书与其他资料。",
  "Customer account": "客户中心",
  "Dealer resources": "经销商资料",
  "Title or tag": "标题或标签",
  "Resource type": "资料类型",
  All: "全部",
  Language: "语言",
  "All languages": "所有语言",
  Filter: "筛选",
  "Clear filters": "清除筛选",
  resources: "份资料",
  "KB · Version": "KB · 版本",
  Published: "发布时间",
  "Resources are temporarily unavailable. Please try again.":
    "资料暂时无法加载，请稍后重试。",
  "No published files match these filters.": "暂无符合筛选条件的已发布文件。",
  "Frequently asked questions": "常见问题",
  Search: "搜索",
  "All products and general questions": "所有商品与通用问题",
  "No published questions match your search. Please contact support.":
    "暂无符合搜索条件的已发布问题，请联系客服。",
  "Support & Downloads": "支持与下载",
  "Manuals, certificates and FAQs. Dealers can access restricted documents after sign-in.":
    "查看说明书、证书和常见问题。经销商登录后可访问授权资料。",
  "Search FAQs": "搜索常见问题",
  "Browse downloads": "浏览下载资料",
  "No public downloads have been published yet.": "暂无已发布的公开下载资料。",
  "No FAQs have been published yet. Use the contact form if you need help.":
    "暂无已发布的常见问题。如需帮助，请通过联系表单咨询。",
  "Verify your email": "验证邮箱",
  "Complete the one-time verification before signing in.":
    "请完成邮箱验证后登录。",
  "Email verified.": "邮箱验证成功。",
  "Need a fresh link?": "需要新的验证链接？",
  "Resend verification email": "重新发送验证邮件",
  "If the account is awaiting verification, a new link is on the way.":
    "如果账号仍待验证，我们将发送新的验证链接。",
  "Order details": "订单详情",
  "Back to": "返回",
  "· Payment": "· 支付状态",
  "Current MFA code": "当前动态验证码",
  Charges: "费用明细",
  "Order items": "订单商品",
  Ordered: "订购数量",
  Shipped: "已发货",
  Returned: "已退货",
  "Line total": "小计",
  quantity: "数量",
  Payment: "付款",
  "Inventory held until": "库存预留截止时间",
  ". Unpaid orders expire automatically.": "。未付款订单到期后自动关闭。",
  "Demo payment session. No real money is charged.":
    "演示支付，不会产生真实扣款。",
  "Cancellation reason": "取消原因",
  "Cancel unpaid order": "取消未付款订单",
  Download: "下载",
  "Reorder at current prices": "按当前价格再次购买",
  "Create a shipment": "创建发货单",
  "Select quantities above. Each shipment removes only those reserved units.":
    "请在上方选择发货数量，每次发货仅扣减相应的预留库存。",
  Carrier: "承运商",
  "Tracking number": "物流单号",
  "Tracking URL (optional)": "物流查询链接（选填）",
  "Record shipment": "确认发货",
  "Shipment tracking": "物流跟踪",
  "Track shipment": "查询物流",
  "Request a return or exchange": "申请退换货",
  "Select the return quantities in the items table.":
    "请在商品表格中选择退换货数量。",
  Resolution: "处理方式",
  "Return for refund": "退货退款",
  Exchange: "换货",
  Reason: "原因",
  "Additional details": "补充说明",
  "Submit request": "提交申请",
  "Returns & exchanges": "退换货记录",
  "Download private photo:": "下载私有图片：",
  "Replacement carrier": "换货承运商",
  "Replacement tracking number": "换货物流单号",
  "Ship exchange replacement": "确认换货发出",
  "Decision note": "处理说明",
  "Next status": "下一状态",
  "Update return": "更新退货状态",
  "Issue a refund": "发起退款",
  "Amount (": "金额（",
  "Related return (optional)": "关联退货（选填）",
  "Order adjustment": "订单调整",
  "Refund reason": "退款原因",
  "Submit refund": "提交退款",
  "Refund history": "退款记录",
  "Provider reference": "支付平台参考号",
  "Provider result": "支付平台处理结果",
  SUCCEEDED: "成功",
  FAILED: "失败",
  "Record external result": "记录外部处理结果",
  "Order history": "订单历史",
  "Search by country, state, city, postal code or name":
    "按国家、省份、城市、邮编或名称搜索",
  "Dealer map": "经销商地图",
  "World coordinate map with dealer locations": "显示经销商位置的世界坐标地图",
  "Opening information:": "营业信息：",
  "Authorized categories:": "授权商品分类：",
  "Store details": "门店详情",
  "Visit website": "访问网站",
  "Street map": "街道地图",
  "No published dealers match this location.": "此地区暂无已公开的经销商。",
  "Contact our team": "联系我们的团队",
  "for buying options.": "以了解购买方式。",
  "Selected:": "已选择：",
  "Search suggestions": "搜索建议",
  "Calculating…": "正在计算…",
  "Review current prices & totals": "查看当前价格与总费用",
  "Demo payment: no real money is charged.": "演示支付：不会产生真实扣款。",
  "Payment is confirmed by the configured provider integration.":
    "付款结果由已配置的支付服务确认。",
  "Compare products": "商品比较",
  "Sending…": "正在发送…",
  "Send message": "发送留言",
  "Send reset instructions": "发送重置说明",
  "Explore the collection": "浏览此系列",
  "Saving…": "正在保存…",
  "Save new password": "保存新密码",
  "Verifying…": "正在验证…",
  "Verify email": "验证邮箱",
  orders: "订单列表",
  account: "账号中心",
  "Ship quantity": "发货数量",
  "Return quantity": "退货数量",
  Ship: "发货",
  Return: "退货",
  "Simulate success": "模拟支付成功",
  "Simulate failure": "模拟支付失败",
  "Cancel payment": "取消支付",
  "Continue payment": "继续付款",
  "Start payment": "开始付款",
  "Map data © OpenStreetMap contributors": "地图数据 © OpenStreetMap 贡献者",
  "Select a dealer to open its street map": "选择经销商以查看街道地图",
  "Search products, articles, FAQs and downloads":
    "搜索商品、文章、常见问题和资料",
  "This content is available in English while its translation is being prepared.":
    "此内容的中文译文尚未发布，当前显示英文原文。",
  "Content unavailable": "内容无法加载",
  "Shopping cart": "购物车",
  Checkout: "结算",
  "Dealer not found": "未找到经销商",
  "Authorized WEMOVE dealer": "WEMOVE 授权经销商",
  "Unable to process the request.": "暂时无法处理请求，请稍后重试。",
  "This reset link is missing its token.":
    "此重置链接不完整，请重新申请密码重置。",
  "Passwords do not match.": "两次输入的密码不一致。",
  "Unable to reset the password.": "无法重置密码，请重新申请链接后重试。",
  "This verification link is missing its token.":
    "此验证链接不完整，请重新申请验证邮件。",
  "Unable to verify this email.": "无法验证邮箱，请重新申请验证邮件。",
  "Unable to resend verification.": "无法重新发送验证邮件，请稍后重试。",
  "You are unsubscribed. Transactional emails are unaffected.":
    "您已取消订阅，订单等服务邮件仍会正常发送。",
  "Your subscription is confirmed. Bookmark this link to unsubscribe at any time.":
    "订阅已确认。保存此链接，您可以随时取消订阅。",
  "Unable to update subscription": "无法更新订阅状态，请稍后重试。",
  "Choose at most five attachments": "最多选择五个附件。",
  "Each attachment must be at most 5 MB": "每个附件不能超过 5 MB。",
  "Your message has been received. A confirmation email includes your request reference.":
    "留言已收到。确认邮件中包含本次请求的编号。",
  "We could not send your message. Please try again.":
    "留言发送失败，请稍后重试。",
  "General question": "一般咨询",
  "Product inquiry": "商品咨询",
  "Order support": "订单服务",
  "Dealer support": "经销商服务",
  "Privacy request": "隐私请求",
  "Cart unavailable": "购物车暂时无法加载。",
  "Unable to calculate totals": "无法计算总费用，请稍后重试。",
  "Unable to place order": "无法提交订单，请稍后重试。",
  recipient: "收件人",
  phone: "电话",
  "country (ISO code)": "国家或地区（ISO 代码）",
  "state / region": "省份或地区",
  city: "城市",
  "postal code": "邮政编码",
  "address line 1": "详细地址",
  "address line 2 (optional)": "补充地址（选填）",
  Shipping: "配送",
  Billing: "账单",
  Items: "商品金额",
  Discount: "优惠",
  Tax: "税费",
  Total: "合计",
  "United States": "美国",
  "United State": "美国",
  China: "中国",
  Germany: "德国",
  France: "法国",
  "United Kingdom": "英国",
  "Play guide": "玩法指南",
  "Move outside": "户外运动",
  "Build balance": "锻炼平衡",
  "Play together": "一起玩乐",
  "Built to move": "为运动而设计",
  "Toys that invite action, not more screen time.":
    "激发主动运动，减少屏幕时间。",
  "Ready for real life": "为日常生活而准备",
  "Clear guidance for families, schools and retailers.":
    "为家庭、学校与零售商提供清晰的指导。",
  "Made to play again": "值得反复玩乐",
  "Simple formats that stay fun beyond day one.":
    "简单易懂的玩法，让乐趣持续发生。",
  "{count} products": "{count} 款商品",
  "From {price}": "{price} 起",
  "Age guidance": "适龄建议",
  Ages: "年龄范围",
  Scenes: "适用场景",
  Skills: "锻炼能力",
  "How to play": "玩法指南",
  Availability: "供货情况",
  "Weight (g)": "重量（克）",
  "Starting price": "起售价",
  IN_STOCK: "有货",
  OUT_OF_STOCK: "缺货",
  LOW_STOCK: "库存紧张",
  PREORDER: "预售",
  PREORDER_ONLY: "仅接受预订",
  INDOOR: "室内",
  OUTDOOR: "户外",
  SCHOOL: "学校",
  HOME: "家庭",
  PARTY: "聚会",
  Balance: "平衡",
  Coordination: "协调",
  "Motor skills": "运动技能",
  balance: "平衡",
  coordination: "协调",
  ALL: "全部",
  PRODUCT: "商品",
  ARTICLE: "文章",
  FAQ: "常见问题",
  DOWNLOAD: "下载资料",
  MANUAL: "说明书",
  CERTIFICATE: "证书",
  IMAGE: "图片",
  CATALOG: "商品目录",
  OTHER: "其他",
  en: "English",
  zh: "中文",
  English: "English",
  Chinese: "中文",
  "Saved successfully.": "保存成功。",
  "Loading order…": "正在加载订单…",
  "Changed my mind": "不再需要",
  "Incorrect delivery address": "收货地址填写有误",
  "Ordered the wrong items": "选错商品",
  "Delivery estimate is too long": "预计配送时间过长",
  invoice: "发票",
  receipt: "收据",
  "packing list": "装箱单",
  "Image download expired or is unavailable":
    "图片下载链接已过期或暂时不可用。",
  "Image unavailable": "图片暂时不可用。",
  REFUND: "退款",
  EXCHANGE: "换货",
  REQUESTED: "已申请",
  RECEIVED: "已收货",
  PARTIALLY_REFUNDED: "部分退款",
  REFUNDED: "已退款",
  EXPIRED: "已过期",
  RETAILER: "零售商",
  DISTRIBUTOR: "分销商",
  "Online store": "线上商店",
  "Physical store": "实体门店",
  "Street map for {name}": "{name}的街道地图",
  "{name} logo": "{name}标志",
  "{count} results": "{count} 条结果",
  "{count} resources": "{count} 份资料",
  "Product {number}": "商品 {number}",
  "Download {document}": "下载{document}",
  "{status} · Payment {payment}": "{status} · 支付状态：{payment}",
  "Version {version}": "版本 {version}",
  "Published {date}": "发布时间：{date}",
  Subtotal: "商品小计",
  "Amount ({currency})": "金额（{currency}）",
  checkout: "提交订单",
  "manual create": "人工创建订单",
  "shipment create": "创建发货记录",
  "return request": "申请退换货",
  "return update": "更新退换货记录",
  "exchange shipment": "换货发出",
  "refund create": "发起退款",
  "refund result": "退款结果",
  "payment update": "更新付款状态",
  "payment succeeded": "付款成功",
  "payment failed": "付款失败",
  cancel: "取消订单",
  cancelled: "已取消",
  expired: "已过期",
};
