const messages: Record<string, Record<string, string>> = {
  zh: {
    "Cookie consent": "Cookie 使用偏好",
    Products: "产品",
    "Play & Learn": "玩乐与学习",
    Dealers: "经销商",
    Support: "支持",
    About: "关于品牌",
    Contact: "联系",
    "Dealer Portal": "经销商中心",
    Account: "账户",
    Administration: "管理后台",
    Cart: "购物车",
    Search: "搜索",
    Menu: "菜单",
    Shop: "选购",
    "All Products": "全部产品",
    Compare: "产品比较",
    Company: "品牌",
    "Support & Downloads": "支持与下载",
    "Quality & Safety": "品质与安全",
    "Contact Us": "联系我们",
    "For Business": "合作伙伴",
    "Become a Dealer": "申请成为经销商",
    "Dealer Sign in": "经销商登录",
    "Unified sign in": "统一账号登录",
    Privacy: "隐私政策",
    Terms: "使用条款",
    "Cookie settings": "Cookie 设置",
    "Currency is shown with each price.": "币种随价格显示。",
    "Adult-purchase only.": "仅限成年人购买。",
    "Wooden marble runs, STEM learning and craft innovation.":
      "原木滚珠轨道积木、STEM 教育与木作创新。",
    "Your privacy choices": "隐私选择",
    "Essential only": "仅必要 Cookie",
    "Allow analytics": "允许统计",
    "Essential cookies keep sign-in and your cart working. Optional analytics help us improve the site. You can change this in Cookie settings.":
      "必要 Cookie 用于登录和购物车。可选统计帮助改进网站，可随时在 Cookie 设置中更改。",
    "WEMOVE ideas and updates": "订阅 WEMOVE 灵感与动态",
    Email: "邮箱",
    Subscribe: "订阅",
    "I agree to the privacy policy and to receive marketing emails.":
      "我同意隐私政策，并愿意收到营销邮件。",
    "Check your email to confirm your subscription.": "请查看邮件并确认订阅。",
  },
  fr: {
    Products: "Produits",
    "Play & Learn": "Jouer et apprendre",
    Dealers: "Revendeurs",
    Support: "Assistance",
    About: "À propos",
    Contact: "Contact",
    "Dealer Portal": "Espace revendeur",
    Account: "Compte",
    Administration: "Administration",
    Cart: "Panier",
    Search: "Rechercher",
    Menu: "Menu",
    Shop: "Boutique",
    "All Products": "Tous les produits",
    Compare: "Comparer",
    Company: "Entreprise",
    "Support & Downloads": "Assistance et ressources",
    "Quality & Safety": "Qualité et sécurité",
    "Contact Us": "Nous contacter",
    "For Business": "Professionnels",
    "Become a Dealer": "Devenir revendeur",
    "Dealer Sign in": "Connexion revendeur",
    "Unified sign in": "Connexion au compte",
    Privacy: "Confidentialité",
    Terms: "Conditions",
    "Cookie settings": "Paramètres des cookies",
    "Currency is shown with each price.": "La devise figure avec chaque prix.",
    "Adult-purchase only.": "Achat réservé aux adultes.",
    "Active play toys for kids & families.":
      "Des jeux actifs pour les enfants et les familles.",
    "Your privacy choices": "Vos choix de confidentialité",
    "Essential only": "Nécessaires uniquement",
    "Allow analytics": "Autoriser les statistiques",
    "Essential cookies keep sign-in and your cart working. Optional analytics help us improve the site. You can change this in Cookie settings.":
      "Les cookies nécessaires assurent la connexion et le panier. Les statistiques facultatives nous aident à améliorer le site. Vous pouvez modifier votre choix dans les paramètres des cookies.",
    "WEMOVE ideas and updates": "Idées et actualités WEMOVE",
    Email: "Adresse e-mail",
    Subscribe: "Recevoir les actualités",
    "I agree to the privacy policy and to receive marketing emails.":
      "Je consens à la politique de confidentialité et aux e-mails promotionnels.",
    "Check your email to confirm your subscription.":
      "Consultez votre messagerie pour confirmer votre inscription.",
  },
  de: {
    Products: "Produkte",
    "Play & Learn": "Spielen und lernen",
    Dealers: "Händler",
    Support: "Hilfe",
    About: "Über uns",
    Contact: "Kontakt",
    "Dealer Portal": "Händlerportal",
    Account: "Konto",
    Administration: "Verwaltung",
    Cart: "Warenkorb",
    Search: "Suchen",
    Menu: "Menü",
    Shop: "Shop",
    "All Products": "Alle Produkte",
    Compare: "Vergleichen",
    Company: "Unternehmen",
    "Support & Downloads": "Hilfe und Downloads",
    "Quality & Safety": "Qualität und Sicherheit",
    "Contact Us": "Kontakt aufnehmen",
    "For Business": "Geschäftskunden",
    "Become a Dealer": "Händler werden",
    "Dealer Sign in": "Händleranmeldung",
    "Unified sign in": "Kontoanmeldung",
    Privacy: "Datenschutz",
    Terms: "Bedingungen",
    "Cookie settings": "Cookie-Einstellungen",
    "Currency is shown with each price.": "Die Währung steht bei jedem Preis.",
    "Adult-purchase only.": "Kauf nur durch Erwachsene.",
    "Active play toys for kids & families.":
      "Bewegungsspiele für Kinder und Familien.",
    "Your privacy choices": "Ihre Datenschutzauswahl",
    "Essential only": "Nur notwendige Cookies",
    "Allow analytics": "Statistik erlauben",
    "Essential cookies keep sign-in and your cart working. Optional analytics help us improve the site. You can change this in Cookie settings.":
      "Notwendige Cookies ermöglichen Anmeldung und Warenkorb. Freiwillige Statistiken helfen uns, die Website zu verbessern. Ihre Auswahl können Sie in den Cookie-Einstellungen ändern.",
    "WEMOVE ideas and updates": "WEMOVE-Ideen und Neuigkeiten",
    Email: "E-Mail",
    Subscribe: "Abonnieren",
    "I agree to the privacy policy and to receive marketing emails.":
      "Ich stimme der Datenschutzerklärung und dem Empfang von Werbe-E-Mails zu.",
    "Check your email to confirm your subscription.":
      "Bitte bestätigen Sie das Abonnement über die E-Mail.",
  },
};
export function ui(locale: string, message: string) {
  return (
    messages[locale]?.[message] ??
    messages[locale.split("-")[0]]?.[message] ??
    message
  );
}
