ALTER TABLE "Order" ADD COLUMN "calculationSnapshot" JSONB NOT NULL DEFAULT '{}';
ALTER TABLE "OrderItem" ADD COLUMN "priceSource" TEXT NOT NULL DEFAULT 'MSRP', ADD COLUMN "weightGrams" INTEGER NOT NULL DEFAULT 0;
